### ISSUE TITLE
Checking consistency of parameters in use

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#101]
The current problem with the multi-curve support for tests (https://github.com/nucypher/pyUmbral/issues/54) is caused by a lack of consistency of the parameters in use (https://github.com/nucypher/pyUmbral/issues/99). Apart from solving that problem, it's probably a good idea to include some additional checks so it's not possible to have stuff with different parameters (e.g., different curves) at the same moment.

**Comment by KPrasch** [comment]
Fixed in PR #102
