### ISSUE TITLE
When do we expect pyUmbral to be ready to implement in the KMS?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#11]
Until @tuxxy corrected me this morning, I was under the impression that this project was ready to begin implementing in the KMS.

Quoting @tuxxy: 

> Point and BigNum are utility classes for us to implement the Umbral schema in a way that works better as a layer between OpenSSL and Cryptography.io. I don't think we're finished in entirely building out this layer yet and these should not be implemented, in the raw, on the KMS. I'm leaning towards developing a Key class (need to talk to David about this) in Umbral and allowing you either to inherit it or build a new Key class that has an umbral.Key as a property or something.

Putting aside for a moment the matter of whether a `Key` class is or isn't a good idea, do y'all (@cygnusv and @tuxxy) have a sense of when we can start to move some of the KMS logic from the current crypto API to pyumbral?

**Comment by tuxxy** [comment]
Probably when we have all the specifics on serialization and and ciphertext formation figured out.

It's not that far off, we just need to get some details figured out first.

**Comment by cygnusv** [comment]
For example, currently the symmetric encryption part (i.e., the part that consumes the key inside the Capsules and handles the actual encryption/decryption of the data) is handled completely outside Umbral. I think this is confusing. tuxxy and I have to think of how to provide a unified API for this

**Comment by michwill** [comment]
That being said, I don't think we'll immediately use correctness checking in the first working implementation. So it's ok if things are somewhat unsettled on the correctness checking front at first, if this allows to get the first usable implementation faster

**Comment by cygnusv** [comment]
@michwill That's fine. Should we make some kind of priority list wrt to Umbral, so we can focus on the top ones? For starters, I think serialization of all the capsule- and kFrag-related classes should be top priority.

**Comment by michwill** [comment]
@cygnusv yes, I think that is indeed the required minimum
