### ISSUE TITLE
BigNum.__hash__ - is this what we want?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#116]
Two things:

1) Do we actually need `BigNum` to be hashable?
2) If it's going to be, which I guess is OK, do we want to use material to represent it that is less likely to leak sensitive info in a log emission or whatever?

**Comment by cygnusv** [comment]
> can't Capsule._attached_cfrags just be a list?

Sure, the only reason it was a dict was because at some moment I iterate over the keys, but we can do it with a list.

Since that's the only reason I think we needed `BigNum.__hash__()`, I think we can remove it then.
