### ISSUE TITLE
Should we break up Umbral wrt to the characters?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#12]
Currently Umbral and all its auxiliary code is implemented in a single file, where all the PRE functionality is included in the same class. Does it make sense to separate the code according to the characters?

- Alice: encapsulate, decapsulate_original, split_rekey
- Bob: decapsulate_reencrypted, check_challenge
- Ursula: reencrypt, challenge

**Comment by tuxxy** [comment]
Well, if we break it up, I can see splitting it between an "Encryptor" and a "Proxy", but not a "Decryptor".

I don't think we need three different "characters" here, but I can see two where the "Encryptor" has `encapsulate`, `decapsulate_original`, `split_rekey`, `decapsulate_reencrypted`, and `check_challenge`. And where "Proxy" has `reencrypt`, and `challenge`.

**Comment by tuxxy** [comment]
Obviously, we should have a better name for a class than "Encryptor".

**Comment by tuxxy** [comment]
Sorry for commenting over and over again, but I actually really like this idea.

It allows us, in the code, to separate out the client capabilities in the KMS from the Proxy node capabilities.

**Comment by michwill** [comment]
Yes, exactly my thought also

**Comment by cygnusv** [comment]
> It allows us, in the code, to separate out the client capabilities in the KMS from the Proxy node capabilities.
Yes, that was exactly my intention

**Comment by tuxxy** [comment]
@cygnusv Are you taking this on, or can I?

Also, any recommendations for the Alice/Bob name? I was thinking `Umbral` for Alice/Bob and `UmbralProxy` for Ursula.

**Comment by cygnusv** [comment]
I can take this. The names are fine for me :)

**Comment by jMyles** [comment]
I've been thinking about this one, and I'm finding myself less certain.  I kinda wish for a module which simply contains all the functions required for a coherent PRE scheme, and with no accounting for which Characters might be built out of it at a higher level.

I'm not terribly concerned with splitting up the "proxy" vs "client" capabilities at this low level.  It's possible that we'll want to build a Character later who can be both Ursula *and* Alice, or Ursula *and* Bob.

We've already talked about Victor, who will have capabilities consistent with Bob but who will be run from a proxy node.  Where does that fit in?

Let me direct you to a comment by @michwill, which I think paints a good picture of a simple, flat API that is more in keeping with my vision:

https://github.com/nucypher/nucypher-kms/issues/137#issuecomment-348661406

Also (and on the other hand), I do definitely think that the Characters don't really make sense living in the KMS.  My hope is that, after we get to at least a working, demonstrable product, that we take some time to pull them out before adding more of them (or more features to them / to the KMS).  I think it makes sense for them to perhaps live in their own project.

**Comment by cygnusv** [comment]
@jMyles I see your point. I think that either approach is reasonable as long as it is well justified. At the same time, there is no problem in continuing as it currently is and decide later. I'll leave this issue then.

**Comment by tuxxy** [comment]
I think I disagree here. Separating out the methods into their own classes
is not characterizing them. We're not giving them the names of Alice, Bob,
or Ursula; we're just calling them `Umbral` for threshold split key
encryption, and `UmbralProxy` for Re-encryption.

I think separating them out is ultimately good logic and keeps our code
cleaner and more readable.

-tux

**Comment by jMyles** [comment]
@tuxxy: It's completely possible that you're right and, after seeing it, I'll see the light.

But from here, I'm having trouble even understanding what we're talking about:

What is an `Umbral`?  What do I get when I instantiate one?  What's the difference between the `Umbral` class and an instance of that class?  Are there any methods that mutate an `Umbral`?  If I have two umbral instances, how do I know which one to use?  (same questions all apply to an `UmbralProxy`).

Neither an `Umbral` nor an `UmbralProxy` seem like a class of things to me.  To the degree that they're distinguishable, they seem like different namespaces for functions (ie, modules).  But are you really sure that at this early stage your notion of how to coherent split them is the right one?

I can see separating correctness from the rest of the project; that seems clean.

`from umbral.crypto import reencrypt, combine, split_rekey`
`from umbral.correctness import challenge, check_challenge`

Seems reasonable to me (although I can imagine `Challenge` being a class!).

**Comment by michwill** [comment]
Actually, what @jMyles says sounds reasonable indeed. There are advantages keeping all those things as functions, and I also prefer to keep all the cryptographic function in the same namespace more or less (they're not heavy). I do like to see encrypt/decrypt/reencrypt/combine kind of together, it makes them easy to audit (wdyt @tuxxy ?).

Correctness can be separated out (it makes sense logically), but I can entirely imagine that it can't be separated well enough for technical reasons (not sure if it is the case or not).

**Comment by tuxxy** [comment]
Alright, well I'm fine leaving it as is for the time being. Maybe
separating out correctness, but not sure about the implications of moving
that out. David, what do you think about that?

This is quite fine with me, then. :)

**Comment by cygnusv** [comment]
I would leave everything as it is, then. I also agree that there are many advantages for keeping all the crypto functions in the same namespace, but that also includes correctness. It is intimately related, and its relatively small in comparison to the rest, so I will keep everything together then. 

My initial intention was motivated by the different nature of the two types of actors in NuCypher KMS: users (who do everything not related to re-encryption) and Ursulas (who only do re-encryption-related stuff). It kinda made sense to me to separate those functionalities, but nevertheless I agree that there are other reasons to keep everything together.
