### ISSUE TITLE
KFrag.bn_id can be safely changed to a bitstring ID

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#123]
In previous versions of Umbral, we needed `KFrag.bn_id` to be a `BigNum`. This is not necessary anymore.

**Comment by tuxxy** [comment]
It can effectively be a bytestring? What would the bytestring be of?

**Comment by cygnusv** [comment]
I forgot to mention it should be a random bytestring, for example, of 32 bytes.

**Comment by tuxxy** [comment]
Alright, presumably, it must be the size of the order of the curve used?

**Comment by cygnusv** [comment]
Yes, since we use it to derive a `BigNum`, which has the order of the curve.
