### ISSUE TITLE
Guidelines for naming variables in classes with cryptographic material

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#124]
Some guidelines for the imminent renaming of internal variables:
- Internal variables should not be considered public, so they should start with an underscore (e.g., `_bn_key`)
- When possible, add a prefix to the variable name that helps to understand its type (e.g., `_bn_key` is of type `BigNum`)
- When possible, use a self-explanatory name (e.g., `_bn_key`). However, although self-explanatory names are nice, avoid make them too long (e.g., `_point_noninteractive` is better than `_point_eph_noninteractive_transformation`). 
- We allow arbitrary names when there's no immediate functionality associated to the variable (e.g., `_point_e`). In this case, the preference is to tend to one-letter names, as it's customary in scientific literature.

What do you think?

**Comment by michwill** [comment]
Looks good to me. Of course, unless results in `_bn_key_very_long_name_like_usually_in_java`

**Comment by tuxxy** [comment]
I don't think this issue needs to be open anymore.
@cygnusv If you give me the go ahead, I'll close it, or you can do it yourself.

If we need to keep these guidelines, then they should probably be moved into #125.
