### ISSUE TITLE
Use `BN_clear_free` instead of `BN_free` on private values.

### ISSUE THREAD

**Issue by tuxxy** [nucypher/pyUmbral#13]
I got PRs pulled into Cryptography.io for implementing and exposing `BN_clear_free` from OpenSSL.

This improves the security upon `BN_free` by first zeroing out the memory then freeing it.

We should use `BN_clear_free` in places where there are private values (ie: practically everywhere).

**Comment by cygnusv** [comment]
Good. I was going to ask you about this, but didn't know what was the good way to do it. I guess you can handle this, right?

**Comment by tuxxy** [comment]
Yeah, I can. The issue is that we didn’t have anything exposed via OpenSSL that would allow me to use it. My PR on cryptography.io <http://cryptography.io/> got merged. We’ll probably have to wait a bit for the next release to actually implement it, I think.

**Comment by tuxxy** [comment]
Currently blocked and awaiting an upstream cryptography.io release -- #16

**Comment by tuxxy** [comment]
Fixed in #16.
