### ISSUE TITLE
Design decision: Key class?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#14]
I quoted @tux in #11, saying "I don't think we're finished in entirely building out this layer yet. [Point and Bignum] should not be implemented, in the raw, on the KMS."

So: are we going to do a Key class?

I'm in a holding pattern on our `Bob` class in the KMS until either a Key API is available *or* we develop a temporary shim to make the `PublicKey` class that we use in the KMS compatible with `Bignum` / `Point`.

**Comment by cygnusv** [comment]
I think that we could try to make it compatible with cryptography.io's PublicKey. That shouldn't take long, I believe, plus, it makes sense since we are using cryptography.io in our backend.

**Comment by jMyles** [comment]
Beautiful - that's an ideal situation I think.

**Comment by Tux** [comment]
Please use the correct @Tuxxy for this issue, as *I* am not interrested

**Comment by jMyles** [comment]
Ahh yes, my apologies @tux.  Hope you are well.

@tuxxy: What do you think?  :-)

**Comment by Tux** [comment]
I am, thank you. Enjoy your project, hope all goes as planned

**Comment by tuxxy** [comment]
It's impossible to use cryptography.io for handling a `Key` class. Cryptography.io only exposes specific key components e.g. `EllipticCurvePrivateKey`. 

Unless you want to instantiate multiples of `EllipticCurvePrivateKey` and `EllipticCurvePublicKey`, which I think is a bad idea and quite bulky. 

If we need a `Key` class, it should be specific to pyUmbral and clearly scoped/defined. We expect others to use this library as 1) a reference implementation for @cygnusv Umbral schema and 2) for things that may not be related to the KMS.

One of the major points I see for a `Key` class would be for the user private and public keys. We could utilize cryptography.io DER serialization to allow storage. This will also handle encryption of the key material.

Until this is scoped and defined, we can't really continue with this. Scoping and definition should be left up to discussion on a different issue.

**Comment by jMyles** [comment]
@tuxxy: I don't really understand whether your last comment amounts to a "yes" or a "no" on this decision decision.

Based on #17, I presume that you still have a sense in the affirmative.

**Comment by tuxxy** [comment]
Yes, my response was in the affirmative on the stipulation that the class
is thoroughly scoped and defined, and remains specific to the reference
implementation.

**Comment by jMyles** [comment]
I see.  Well, I'm still leaning somewhat to the "no" side, but I can be convinced.
