### ISSUE TITLE
Use bytestringSplitter for from_bytes methods?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#144]
This method is a little gnarly:

https://github.com/nucypher/pyUmbral/blob/master/umbral/fragments.py#L109

Instead of all those `data.read`s, we can just make a splitter for each class.  Thoughts?

**Comment by tuxxy** [comment]
I just hate having to pull in another dependency in there when it can be handled well enough already, though it does look gnarly, it "just works".

@cygnusv What do you think?

**Comment by michwill** [comment]
That was one of the reasons to have it as an individual package. I think, it makes the code more readable and, hence, less error-prone. Of course, provided that the bytestringsplitter is audited

**Comment by cygnusv** [comment]
Current approach it's very error-prone, so I'm all in for doing something better. I actually hate when I have to change something in our current serialization methods.
