### ISSUE TITLE
Add OpenSSL EC_GROUP struct returned in openssl._get_ec_group_by_curve_nid to FFI garbage collector

### ISSUE THREAD

**Issue by tuxxy** [nucypher/pyUmbral#154]
### What is the issue?
1. When `openssl._get_ec_group_by_curve_nid` is called, it returns an OpenSSL `EC_GROUP` struct that is not currently garbage collected. This leads to a memory leak and could potentially cause slowdowns and performance issues for long running processes.
2. When this `EC_GROUP` is added the garbage collector, it causes problems for any function that needs to use this returned `EC_GROUP` because it is immediately freed.

### How to resolve:
1. Since the `EC_GROUP` for a given curve remains static, there is no need to store this variable in memory on any of our backend objects (`Point`, `CurveBN`, etc). Instead, these objects can store the `curve_nid` needed to return the group and use that to access the `EC_GROUP` for the specific backend object.
2. Make (and rename) `openssl._get_ec_group_by_curve_nid` a context manager that handles the `EC_GROUP` very similarly to how `openssl._tmp_bn_mont_ctx` handles a Montgomery context from OpenSSL.
Recommended name is: `_tmp_ec_group_ctx`

### Why?
1. This pattern kills two birds with one stone:
i. Cleans up code by not having to pass in multiple `EC_GROUP` variables to the backend objects. This significantly boosts the simplicity of the backend code and greatly improves code quality.
ii. Decreases potential aberrant and undocumented behavior. This will move us toward trusting OpenSSL more instead of the user-provided input which can lead to security issues and bugs.
2. Makes the backend more usable in general.

**Comment by jMyles** [comment]
![41631091-9051cbbc-73e7-11e8-8d5a-9696c8cc52a5](https://user-images.githubusercontent.com/311973/41882558-75675b26-789e-11e8-84d6-829b94f5570f.jpg)

**Comment by michwill** [comment]
Would it be safe to use the same `EC_GROUP` struct for all the calls which need the group? E.g. having it as a global.
(Although, perhaps, creating and removing it is a cleaner solution)

**Comment by cygnusv** [comment]
@tuxxy Is this solved by the `umbral.curve` PR?

**Comment by tuxxy** [comment]
Theoretically, yes. The issue is that the GC would collect it immediately,
in my experience. @jmyles is this not the case?
