### ISSUE TITLE
Another strange segfault.

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#156]
This time it's `backend._lib.EC_POINT_cmp`, when trying to compare points created when trying to attach a cfrag from one curve and verifying it with a key from another.

**Comment by michwill** [comment]
Oh man, I guess we need to do extra checks on all the points. Otherwise OpenSSL will punish by segfaults.
Of course, that's not how it should be in OpenSSL, imo

**Comment by KPrasch** [comment]
Could this be related to memory leak fixes in PR #178?

**Comment by cygnusv** [comment]
Not really, this is an OpenSSL issue, and I really doubt they'd want to fix it. 

I think we can close this issue too.
