### ISSUE TITLE
Components of a Key class

### ISSUE THREAD

**Issue by tuxxy** [nucypher/pyUmbral#17]
A `Key` class might be created.

This is a discussion of scoping. What should be included in the key class? I propose serialization through cryptography.io DER formatting.

What else should this do?

Reminder: this should be specific to the reference implementation of Umbral, not the KMS itself.

**Comment by michwill** [comment]
How much extra info does der have when we have multiple entities? E.g. if we serialize something like `[BN1, BN2, Point1, Point2]`.
Another consideration is ease of parsing in languages other than Python (and that is what I liked msgpack for).

**Comment by cygnusv** [comment]
What "key" are we talking about here? We have public keys, private keys, and kFrags, all of them different.

**Comment by tuxxy** [comment]
@cygnusv Specifically the keypair that contains the private and public components to be used for communications from `gen_priv` and `priv2pub`, not the other key components.

**Comment by cygnusv** [comment]
ok so it's only the public and private keys, right? That is, an EC point and a bignum. But that's not different from what cryptography.io already offers with EllipticCurvePublicKey and EllipticCurvePrivateKey, right?

**Comment by tuxxy** [comment]
Yep, right. This gives the benefit of serializing as PEM or DER.

**Comment by jMyles** [comment]
I'm not sure I understand here - why can't we use the cryptography.io key classes?

**Comment by tuxxy** [comment]
Well, we can for those. We can't for the other fragment classes.

**Comment by jMyles** [comment]
But that's OK, because those are public, right?  It's just `Point` and `BigNum` that you're looking to keep internal, right?

**Comment by tuxxy** [comment]
I'm sorry, I'm not following your point. The only public key is _the_ public key. The private key is kept secret.

You were wanting a `Key` class for the KMS that you could possibly abstract upon. Do you want me to represent these as `EllipticCurve<Private/Public>Key` objects? You aren't going to have to worry about `Point` or `BigNum` classes in there at all.

**Comment by jMyles** [comment]
I didn't mean "public" in the key exchange sense, but in the logic-organization sense.

As you know, I'm blocked on `Bob` right now in the KMS because you didn't want me to use `Point` / `BigNum` the way they're used in the tests to complete the decapsulation.  

So I'm still waiting for the public interface to use in the KMS.

That's how this whole conversation began, [remember](https://github.com/nucypher/pyUmbral/issues/11)?  :-)

**Comment by tuxxy** [comment]
Ah, right.

So, what properties are you wanting from these components? Depending on how you answer, I don't know if the cryptography.io classes will be enough for you.

**Comment by jMyles** [comment]
Right - good question!

Basically, I want something that can be used the way @michwill depicted here (see his names pub_a and pub_b): https://github.com/nucypher/nucypher-kms/issues/137#issuecomment-348661406

**Comment by tuxxy** [comment]
Right, so you just need the operating keypair's keys exposed to you in a manner that allows you to go --  `api.encrypt(pub_a, <data>)`?

**Comment by jMyles** [comment]
I think so, right?  Does that make the most sense to you?

That's certainly the most pluggable way to move forward with the logic we already have.

**Comment by tuxxy** [comment]
I think we could maybe have a few Key classes:

`UmbralPublicKey` and `UmbralPrivateKey` which can handle serialization and you can build for operations on these two keys.

@cygnusv Any thoughts here? It would cause some `PRE` API changes due to having to use these objects, or we can avoid using these objects with internal operations. I'm leaning towards the latter..

**Comment by cygnusv** [comment]
I don't mind either of the options. Whatever works better for you and @jMyles
