### ISSUE TITLE
Versioning Plan

### ISSUE THREAD

**Issue by KPrasch** [nucypher/pyUmbral#185]
https://semver.org/ describes a useful way to version software projects.  

I suggest our initial four versions can be:
 - v0.1.0-alpha
 - v0.1.0-beta 
 - v0.1.0-rc.1
 - v0.1.0

Does anyone else have thoughts on this? 
For this Issue to be closed:  
- Lets choose a version format
- Make a release cycle / versioning plan

**Comment by cygnusv** [comment]
+1 for v0.1.0-<tag>

Anything else is completely arbitrary and as soon as we fix in stone the public API we just bump to v1.0.0.

**Comment by KPrasch** [comment]
OK, Agreed - sounds like semver is a good fit for us then.

**Comment by tuxxy** [comment]
I also agree. Before we close this issue, would we like to agree on a current version?

**Comment by KPrasch** [comment]
I suggest that we start a GH project to encapsulate issues pertaining to the first release. I think an alpha tag makes sense Initially to indicate we're issuing pre-releases. How's v0.1.0-alpha?

**Comment by KPrasch** [comment]
Looks like there is enough discussion to close the Issue.  We'll use semver starting with `v0.1.0-alpha`.
