### ISSUE TITLE
Move fragment and capsule classes into their own file?

### ISSUE THREAD

**Issue by tuxxy** [nucypher/pyUmbral#19]
The Capsule and Fragment classes are quite lengthy due to serialization code, would it be ideal to move those out into their own files and import them in the umbral file?

**Comment by cygnusv** [comment]
I would not oppose to that, but I prefer to keep it together. Currently it's barely over 400 lines of code, that doesn't seem much to me.

**Comment by tuxxy** [comment]
I could probably just move the `PRE` class above the fragment classes. I just hate `PRE` having to scroll through all the serialization code to reach that class.

**Comment by cygnusv** [comment]
That's fine :)
