### ISSUE TITLE
Umbral data class serialization

### ISSUE THREAD

**Issue by tuxxy** [nucypher/pyUmbral#2]
Moving discussions between @cygnusv and I from Email to GitHub!

The Umbral data classes need to have a serialization format. This involves the classes:

1. `RekeyFrag`
2. `CiphertextKEM`
3. `CiphertextFrag`
4. `CiphertextCombined`
5. `ChallengeResponse`

Inside of these classes, we don't have very informative names, so maybe we should also consider some naming here so auditors can have an idea of what each component is.

**Comment by cygnusv** [comment]
All these class names can be changed, but I'm afraid it's very difficult to come up with informative names for most of the elements inside them. Let me think about it and propose something here. What I wouldn't like is to make the code to verbose, although I agree that currently it look very cryptic.

**Comment by tuxxy** [comment]
Yeah, I understand that these components might be very difficult to name appropriately.

I don't think we need to be exceptionally verbose and I agree with you on that -- this code should not be verbose.

What I do think is that we could use names that are meaningful and descriptive.

For example, (this isn't actual code, it's just an example I came up with):

Instead of `x`. We can call it `x_coeff`. This is a better name in that it describes `x` as a coefficient.

Where I think we should be verbose is code documentation. In each of these classes, maybe we could give a relatively short overview of how these components are used? For example, `"These components are used in a polynomial for Shamir's Secret Sharing, see the Umbral paper for more information."`

**Comment by tuxxy** [comment]
Handled in #15, awaiting review and merge.

**Comment by tuxxy** [comment]
Merged in #15.
