### ISSUE TITLE
Serializing a Capsule: include frags?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#20]
If Bob is in the process of attaching `CFrags` to a `Capsule`, and he *then* serializes to bytes, don't we want to represent the `CFrags` in the resulting bytestring?  Currently, they're ignored.

**Comment by michwill** [comment]
Why would we need to serialize cfrags? I cannot imagine a situation when we started making a capsule, and then want to continue much later on

**Comment by michwill** [comment]
Although, another question is why current method is better than just `combine(*cfrags)`

**Comment by jMyles** [comment]
@tuxxy points out that a more secure default is for `Bob` to preserve the `Capsule` with, at most, m-1 CFrags.

**Comment by jMyles** [comment]
OK, I suppose this one is dead! :-)
