### ISSUE TITLE
umbral_simple_api.py not working

### ISSUE THREAD

**Issue by alberk8** [nucypher/pyUmbral#203]
Please take a look at the example, there is a change in the API split_rekey parameters and the example is no longer working.

**Comment by cygnusv** [comment]
Sorry for that! We've been focusing in other pending stuff and have neglected such important things. I'll update this in the next hours. Thanks @alberk8 !

**Comment by alberk8** [comment]
Thanks for the prompt reply.  I like the whole concept for proxy re-encryption and you guys are going places once it goes live.   Please get it fixed and I can give it another spin.  Thank you.

**Comment by cygnusv** [comment]
I have a pending PR that solves this problem. It still requires more work, but in the meantime, you have here an [updated example](https://github.com/cygnusv/pyUmbral/blob/038ff6adda64bbb47d5eb183a59ff4cd68765530/docs/examples/umbral_simple_api.py), so you can continue with your work.
