### ISSUE TITLE
not so security

### ISSUE THREAD

**Issue by mccoysc** [nucypher/pyUmbral#240]
i found that,umbral work like the following:
1,symmetric encrypting data in chacha-poly1305 using key derived from ecdh 
2,make the ecdh public key using receiver's public key.
3,receiver derive symmetric key by ecdh using ecdh shared public key.
4,chacha-poly1305 verify and decrypt data.

if in b/s or c/s mode,you can denied the access if chacha-poly1305 verify error.
but in endpoint-to-endpont,is it work?

**Comment by michwill** [comment]
Sorry, we are having a difficult time parsing your question. Can you re-formulate?
