### ISSUE TITLE
I use the function "pre.generate_kfrags" , the "threshold" type is 'UmbralPublicKey' ?

### ISSUE THREAD

**Issue by iSteveyang** [nucypher/pyUmbral#246]
` kfrags = pre.generate_kfrags(alices_private_key, alices_signer, bobs_public_key, 10, 20)`
  
File "/Users/isteveyang/.pyenv/versions/3.7.0/lib/python3.7/site-packages/umbral/pre.py", line 211, in generate_kfrags
    if threshold <= 0 or threshold > N:
TypeError: '<=' not supported between instances of 'UmbralPublicKey' and 'int'

I find it in source code
def generate_kfrags(delegating_privkey: UmbralPrivateKey,
                    receiving_pubkey: UmbralPublicKey,
                    threshold: int,
                    N: int,
                    signer: Signer,
                    sign_delegating_key: Optional[bool] = True,
                    sign_receiving_key: Optional[bool] = True,
                    ) -> List[KFrag]:
threshold type is 'int'
What's wrong with it ?

**Comment by cygnusv** [comment]
Hi @iSteveyang,
it seems you're not passing the arguments in the correct order. You have two options:
* Either use the order described by the source code:
```python
kfrags = pre.generate_kfrags(alices_private_key,
                             bobs_public_key,
                             10,
                             20,
                             alices_signer)
```
* or use keyword arguments in any order, as shown in the README:
```python
kfrags = pre.generate_kfrags(delegating_privkey=alices_private_key,
                             signer=alices_signer,
                             receiving_pubkey=bobs_public_key,
                             threshold=10,
                             N=20)
```
