### ISSUE TITLE
Sending keys to Ursula

### ISSUE THREAD

**Issue by dominic-healid** [nucypher/pyUmbral#248]
Has anyonce can provide sample code for the re-encryption process where Ursulas are involved like sending keys to them and receiving it?

I believe on the sample code it only simulate the logic for sending the receiving fragments from the ursula nodes. 

```
When Alice wants to grant Bob access to open her encrypted messages, she creates re-encryption key fragments, or "kfrags", which are next sent to N proxies or Ursulas.
```

How do we send the kfrags to Ursulas?

**Comment by dominic-healid** [comment]
Upon analyzing it more, I believe Ursulas are part of NuCypher network and this pyUmbral sample code is independent to NuCypher that's why sending the keys to Ursulas are not specified.

**Comment by KebAz** [comment]
That's what I think also.
Thus to send kfrags to Ursulas without using NuCypher, you should implement it yourself.
