### ISSUE TITLE
Input ciphertext must be a bytes object of length >= 12

### ISSUE THREAD

**Issue by KebAz** [nucypher/pyUmbral#253]
Hi,
How to fix this error please?
ValueError: Input ciphertext must be a bytes object of length >= 12
It's occurred when I'm trying to decrypt a message with pre.decrypt().

**Comment by michwill** [comment]
Can you show, how can it be reproduced, and what went as an input?

**Comment by KebAz** [comment]
decrypted_message=pre.decrypt(capsule, private_key, encrypted_message, public_key)
the input values are: 
Capsule:  2fa6717c69a0660
private_key: <umbral.keys.UmbralPrivateKey object at 0x7f850dae0e10> 
encrypted_message: b'\xc8\x90\xdb\x02[y\x12\xf5I\xb0\x18\xe5\x82w\xd2\t\xe2\xb1*\xb4*Wj\xffK\xf4s\xd00\xa9;\xd1'
UmbralPublicKey:0396a209dab2649

**Comment by cygnusv** [comment]
How did you produce such `encrypted_message`?

**Comment by cygnusv** [comment]
I think you're using the parameters of `pre.decrypt()` in an incorrect order. The correct order is specified in the API:
```python
def decrypt(ciphertext: bytes, capsule: Capsule, decrypting_key: UmbralPrivateKey,
            check_proof: bool = True) -> bytes:
```
In your case:
```python
decrypted_message=pre.decrypt(encrypted_message, capsule, private_key)
```
