### ISSUE TITLE
Using Ethereum keys instead of umbral keys ?

### ISSUE THREAD

**Issue by KebAz** [nucypher/pyUmbral#254]
Can we use Ethereum public and private keys instead of umbral keys ?
I want to integrate the proxy re-encryption with Ethereum network by using pyUmbral. And I'm wondering if is it possible to do the encryption and decryption using the Ethereum keys with pyUmbral instead of generating other keys.

**Comment by cygnusv** [comment]
It's possible, since both Umbral and Ethereum use curve `secp256k1`, but why would you want to do that? It's not a great idea to reuse signing keys (as for example, keys used to sign Ethereum transactions) for encryption, and vice versa. We strongly discourage such use case.

**Comment by michwill** [comment]
I think, the best thing is to upload the encrypting pubkeys to Ethereum blockchain. That makes it possible to point ENS to them, etc, while keeping separate from Ethereum keys
