### ISSUE TITLE
A question about collusion safeness

### ISSUE THREAD

**Issue by Whisker17** [nucypher/pyUmbral#255]
After read this [paper](https://raw.githubusercontent.com/nucypher/umbral-doc/master/umbral-doc.pdf) and code,I had a question about safeness of Alice's privatekey.
According to the paper,Bob can get cfrags from proxy,and then decapsulatefrags by skb and pka,and then caculate the symmetric key K by KDF((E' * V')^d).Also,we can know these things:
![image](https://user-images.githubusercontent.com/12571049/72043703-cced5d00-32ec-11ea-97e2-afe898d224c5.png)
![image](https://user-images.githubusercontent.com/12571049/72043730-e098c380-32ec-11ea-89dd-833584c1e58a.png)
![image](https://user-images.githubusercontent.com/12571049/72043739-e5f60e00-32ec-11ea-9bbe-1c4ff31c5558.png)
And we can get E1,i and V1,i from cfrags,does that mean Bob can caculate the Alice's privatekey acording to K=KDF((E * V)^a),because we can transform E' and V' to E and V, so a , which is Alice's privatekey , can be expressed by using known variables.
Hope someone can help me figure this out,I'll appreciate this.

**Comment by cygnusv** [comment]
Hi @Whisker17, if I understood correctly your question, you're asking if knowing `E*V` and `(E*V)^a` is it possible to extract `a`? I'm afraid that's not possible, since in the group where this exponentiation operation occurs, the [discrete logarithm is hard](https://en.wikipedia.org/wiki/Discrete_logarithm#Cryptography).

**Comment by Whisker17** [comment]
> Hi @Whisker17, if I understood correctly your question, you're asking if knowing `E*V` and `(E*V)^a` is it possible to extract `a`? I'm afraid that's not possible, since in the group where this exponentiation operation occurs, the [discrete logarithm is hard](https://en.wikipedia.org/wiki/Discrete_logarithm#Cryptography).

I think you misunderstand what I mean.I think since Bob can get E' and V' from cfrags and then caculate the symmetric key K by K=KDF((E' * V')^d),and for Alice, K=KDF((E * V)^a).Since the symmetric key equals with each other.Does that mean Bob can transform E' to E,V' to V,and then caculate a.Here is my caculate process,I'm not sure whether true or false:
![image](https://user-images.githubusercontent.com/12571049/72066509-bca0a680-331b-11ea-916b-c1e910ea89f0.png)
![image](https://user-images.githubusercontent.com/12571049/72066526-c924ff00-331b-11ea-8b61-29cd14afca96.png)
