### ISSUE TITLE
Is Capsule a mixin?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#28]
On Slack, @michwill said:

> Btw with regards to Umbral I have the following thought. With `encapsulate()` and `decapsulate()`, one can easily implement `encrypt()` and `decrypt()`. But I think we need to make encrypt and decrypt methods for users

> Maybe `PRE` class should also subclass something which creates `encrypt` and `decrypt` functions using any algos which implement encapsulation

> In a way, we can have a _mixin_ which implements encrypt/decrypt using encapsulate/decapsulate, separately from umbral.py. IMO that's important for users of umbral.
And also I think that this mixin should be in pyumbral, not nucypher-kms

Subsequently, the following conversation ensued:

jmyles [1:35 AM]
@michwill: In principle, I agree in full.  In practice, I find that I react with more nuance:

1) I'm not sure that "we" in the sense of PRE authors and reference implementers need to make `encrypt` and `decrypt`, but surely "we" as demonstrars of the capacity for PRE to perform as a cryptographic scheme of viable social worth need to do so, yes.

2) I don't like the idea of PRE being a subclass, mostly because I don't like the idea of PRE being a class.

3) Yes, this mixin was among the scenarios I had imagined when I tried to summon the needs of "other implementers" in my early conversation with @dnunez and @tux.

4) I agree that such an instrument belongs in pyumbral.

Let me suggest a name for this facility:

`Capsule`.

Picture this:

```class Capsule(object):
...
  def encrypt(self, *args, **kwargs):
     return NotImplemented

class WidelyUsefulDEM(object):
...
   def encrypt(self, payload):
      bulk_data, encryption_key = self.perform_locally_relevant_encryption(payload)

    self.encapsulate(..., encyrption_key)

class CapsuleWithDEM(WidelyUsefulDEM, Capsule):
    ...

    def transmit_via_network(network_params):
        ...

```

(edited)
[1:37 AM]
And then, `PRE`, by contrast, is singular and fixed, set as stubborn singletons in a module, using only names to be found in the paper and representing them exclusively as bytes. (edited)
[1:39 AM]
(going to bed; see y'all in the morn)
michwill [2:05 AM]
Huh, having encrypt in a special Capsule is interesting. If it makes a convenient API of course

dnunez [10:25 AM]
I really like the idea of `class WidelyUsefulDEM`
[10:26 AM]
but not so much that encrypt is a method of `Capsule`
tux [10:27 AM]
Yeah, I do too
dnunez [10:27 AM]
it doesn't make sense from the OOP point of view
[10:27 AM]
you don't encrypt a capsule
tux [10:27 AM]
Right
dnunez [10:27 AM]
actually a capsule is just the information you need to decrypt later
[10:28 AM]
`encapsulate` returns a tuple `(symmetric key K, capsule)`
[10:28 AM]
`K` is used during the symmetric encryption (edited)
tux [10:29 AM]
Yeah, a DEM class sounds good to me
dnunez [10:29 AM]
and the final ciphertext is `(capsule, symmetric ciphertext)`
[10:29 AM]
as you can see, during the symmetric encryption you don't use the capsule for anything
[10:30 AM]
it however must be present for decryption, since you first need to `decapsulate` the `capsule` to obtain again `K`
tux [10:30 AM]
Right
[10:31 AM]
@dnunez what about putting a nullable attribute on Capsule `plain_key`?
[10:31 AM]
Then for symmetric encryption, you could pass in the `capsule.plain_key` (edited)
dnunez [10:32 AM]
The idea of `class WidelyUsefulDEM` has some other advantages, since for example, the KDF right now is producing a fixed amounts of bytes (32, if I'm not wrong), so this could be retrieved from the `WidelyUsefulDEM` instance
[10:32 AM]
but I see this instance as something that is used in `PRE`, not in `Capsule`
tux [10:33 AM]
Yeah, that makes sense too
dnunez [10:35 AM]
could you explain more the nullable attribute thing?
tux [10:36 AM]
When you create a capsule, instead of returning a tuple it just adds the key to a `plain_key` attr
[10:37 AM]
Then on encrypt, you pass in the capsule with the plain_key
[10:37 AM]
If it doesn't exist, it'll error
[10:39 AM]
On decrypt, it either a) decrypts the capsule and then performs symmetric decryption or b) checks for `plain_key` before trying to do symmetric decryption.
[10:41 AM]
It'll never be serialized and transferred to anyone, it only exists locally. After performing one `encrypt`, we `del` the plain key attr.
[10:41 AM]
Probably still can be recovered in memory though
dnunez [10:52 AM]
mmmmm
[10:54 AM]
well, that's kind of compatible with @jmyles idea
[10:54 AM]
that's a good
tux [10:55 AM]
Now, this attr can also be on `PRE`
dnunez [10:55 AM]
I still think that my point wrt "you don't encrypt capsules" is still valid
tux [10:56 AM]
That too makes sense
[10:56 AM]
Right
dnunez [10:56 AM]
but the idea of including the key `K` in the capsule could be acceptable
tux [10:57 AM]
It can work, doesn't mean it should though
[10:57 AM]
I'm kinda leaning towards having it in the PRE object
jmyles [12:32 PM]
@dnunez: But look at my example above - you're right!  `Capsule` doesn't have `encrypt`.  It's a mixin that, when used with `WidelyUsefulDEM` becomes `CapsuleWithDEM`, and *that* has `encrypt`.
[12:33 PM]
You don't `encyrpt` a `Capsule`, that's true, but that's not the only way to think about OOP verbs.  In this case, consider that you "encrypt *into*" a `CapsuleWithDEM`.
[12:36 PM]
I don't like it being on the `PRE` because I want `PRE` to be stateless and singular.  I don't want the user mixing it with anything, even a `WidelyUsefulDEM`.  The `PRE` needs to be something like a homomorphic translation of the paper.
[12:36 PM]
(ie, I don't think that `PRE` is properly a class, but a module with functions and private constants) (edited)

**Comment by tuxxy** [comment]
If you're asking us directly if `Capsule` is a mixin, then I would probably disagree. I think @cygnusv would as well. I haven't really seen an encryption library that offers mixins for their ciphertext before, and I don't think I'd like to be the first.

**Comment by jMyles** [comment]
Well, perhaps it's a mistake then to regard the `Capsule` as the exact same abstraction as the Ciphertext.  Isn't that the whole point of the encapsulation metaphor?  The `Capsule` is the *shape* that the Ciphertext is given in order to make it easier to ferry around.  Right?  Otherwise, it's easy to imagine KEM's using the word "encrypt" instead of "encapsulate."

In our case, I think that the ciphertext is simply the three elements injected into the `Capsule` at the end of `PRE.encapsulate`: `pub_u`, `pub_r`, and `s`.  

In fact, I still think that a private `_Ciphertext` class makes some sense (I said this way back in November - see Issue 112 of the KMS project) - it then becomes the type hint for the first parameter of `Capsule`.

Also, it does not appear that we'd be the first project to circulate such a notion as a mixin that includes access to a ciphertext:

* django-encrypted-fields does it: https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py#L36
* A project of which I've never previously heard called slosilo does it: https://github.com/cyberark/slosilo/blob/master/README.md

I don't know if it's an idea who's time has come or not.  But I do know that it's not a *bad* idea.

**Comment by tuxxy** [comment]
In the examples provided, the mixins are used to encrypt a field or an attribute on a class. This specifically references objects that perform encryption. As we have previously said, `Capsule` is not an encrypting object and should be seen as a part of the ciphertext from the output of Umbral.

Simply, this just isn't a model I want to use. It makes sense for Django or slosilo (whatever that is), but not for us.

**Comment by jMyles** [comment]
> As we have previously said, Capsule is not an encrypting object and should be seen as a part of the ciphertext from the output of Umbral.

It's true that you've said that, but so far, you haven't actually advanced an argument for that position.

Obviously to "encapsulate" is to place some particular thing (or set of things) in a `Capsule`.  In other words, the `Capsule` is *not* "part of the ciphertext," instead the ciphertext is part of the `Capsule`.  If you have made a compelling argument to the contrary, and I missed it, then definitely point me to it.

> Simply, this just isn't a model I want to use. It makes sense for Django or slosilo (whatever that is), but not for us.

Well, why?  @michwill asserts that it is a useful model, and I haven't seen any direct responses to his idea.  If this isn't the proper public interface, then where *does* the user go to commit her most treasured works to the `Capsule`?

**Comment by tuxxy** [comment]
The `Capsule` class is an abstraction of our ciphertext to easily allow us to handle it in the reference implementation in a clear and concise manner. The `Capsule` is similar to an alias of "ciphertext". This is how we intended for it to be -- it works very well within a KEM context.

If a mixin object is to be provided, it should be as @michwill said: in a separate part away from umbral.py -- as I have done with the keys. It should not be _the_ source for encryption/decryption. Clearly there is a need for these functions, but not in `Capsule`.

In a KEM scheme, the key material is defined:

A key is randomly sampled such that: `K_symm = {0,1)^n`
`K_enc = Enc(K_pub, K_symm)`
`K_enc` is now clearly the ciphertext of encrypting function `Enc`.

In our use, we are using `Capsule` to be the logical equivalent of `K_enc`. Umbral is a different scheme such that our ciphertext is larger than other schemes and contains more information. Just because this is all under one domain as `Capsule` does not mean that `Capsule` isn't the ciphertext. This is how we treat `Capsule`.

**Comment by jMyles** [comment]
> If a mixin object is to be provided, it should be as @michwill said: in a separate part away from umbral.py

I didn't see where he said that, but I definitely agree.  In fact, this is the reason I don't think that `Capsule` belongs in umbral.py (or where `PRE` goes) and is better placed in its own module, as a public interface.

Let me repeat my question, which I have asked in many fora over the past couple weeks without an answer:

If this isn't the proper public interface, then where does the user go to commit her most treasured works to the `Capsule`?  How do I the user combine my preferred scheme for symmetric encryption with umbral's capacity to place my content in a `Capsule`?

**Comment by tuxxy** [comment]
>If this isn't the proper public interface, then where does the user go to commit her most treasured works to the `Capsule`?

Most likely, `PRE` or a class outside of that.

>How do I the user combine my preferred scheme for symmetric encryption with umbral's capacity to place my content in a `Capsule`?

You don't, you use the Umbral spec'd symmetric encryption function: Salsa20-Poly1305

**Comment by jMyles** [comment]
> Most likely, PRE or a class outside of that.

Show me - give me a sample interface that you think is better than `CapsuleWithDEM`.

> You don't, you use the Umbral spec'd symmetric encryption function: Salsa20-Poly1305

That has not been decided.  I'm still of the mind that it makes sense to be agnostic about the symmetric encryption.

**Comment by tuxxy** [comment]
> Show me - give me a sample interface that you think is better than CapsuleWithDEM.

Alright, but I think elsewhere is better than Github, atm.

> That has not been decided. I'm still of the mind that it makes sense to be agnostic about the symmetric encryption.

Actually, it has. [Check out the Umbral paper, section 3.4](https://github.com/nucypher/umbral-doc/blob/master/umbral-doc.pdf).

It is ideal to be strong about which cipher we choose to prevent users from misusing another cipher, like AES. Salsa20-Poly1305 is perfect because it's authenticated, simple to use, and does great with misuse resistance and usability.

**Comment by jMyles** [comment]
> Actually, it has. Check out the Umbral paper, section 3.4.

I mean, yeah, man, I've read the paper.  But it's still under discussion - that's the whole point here.  

I remain of the mind that we are best placed to give the User public interfaces for both the "inner" and "outer" symmetric keys.  Although we don't need it for the KMS, I don't think it adds any extra work and I think we will want it for subsequent projects.  It seems short-sighted to me to color it outside the spec at this early stage.

...why isn't github a good place to sketch this user interface?

**Comment by tuxxy** [comment]
> I mean, yeah, man, I've read the paper. But it's still under discussion - that's the whole point here.

Well, can you give an argument for not wanting a strictly defined symmetric cipher? For security reasons, I only see positives to restricting the cipher in the standard. This does not mean the user _must_ use whatever DEM method we provide.

> ... give the User public interfaces for both the "inner" and "outer" symmetric keys.

What are "inner" and "outer" symmetric keys? 

I don't like Github for sketching things out, it's not an editor.

**Comment by tuxxy** [comment]
```
class UmbralDEM(object):
    ...

    def encrypt(self, data, pubkey):
        ...

        symm_key, capsule = PRE.encapsulate(pubkey)

        enc_data = nacl.secret.SecretBox(symm_key).encrypt(data)

        return enc_data, capsule

    def decrypt(self, enc_data, capsule, priv_a):
        ...

        symm_key = PRE.decapsulate_reencrypted(priv_a, capsule, ...)

        dec_data = nacl.secret.SecretBox(symm_key).decrypt(enc_data)

        return dec_data

    ...
```

Minus the code for challenge checking, verification, etc etc. Simply `encrypt` and `decrypt`. If you want to make a mixin, make it a mixin. If you want to use it plain, then use it plain. Works both ways.

**Comment by jMyles** [comment]
At a high level, this looks good to me!

**Comment by tuxxy** [comment]
Gonna go ahead and close this issue because it seems resolved.
