### ISSUE TITLE
Change Point operations to multiplicative notation?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#3]
After coding most of Umbral with the current Point class, I have to say that currently it feels weird because it uses an additive notation (i.e., points are added and multiplied by a scalar, rather than multiplied and exponentiated, respectively). The problem is basically with the EC multiplication operation and how it is overloads the Python `*` operator. Right now, multiplying a point by a scalar looks like this: `point * scalar`, which is very odd since it doesn't look like the usual two ways in the literature to express this: 
- Additive notation: `scalar * point`
- Multiplicative notation: `point ** scalar`

I'm afraid there is no solution for this if we want to follow the additive notation. Therefore we can either just leave it like that, or change it to multiplicative notation (like in Charm). The latter implies that EC addition becomes multiplication (`*`), and that EC multiplication becomes exponentiation (`**`)

**Comment by tuxxy** [comment]
So, all you want here is to overload `__pow__` instead of `__mul__` in the `Point` class?

I can make that happen. Let me know.

**Comment by tuxxy** [comment]
To verify in code terms, `EC_POINT_mul` is considered exponentations (a la `**`). And `EC_POINT_add` is considered multiplications (a la `*`)?

We can overload `__mul__` with what is currently `__add__`, and overload `__pow__` with what is currently `__mul__`.

**Comment by tuxxy** [comment]
@cygnusv Informed me that we shouldn't worry about this. I'll close it for now, maybe we'll reopen it in the future.
