### ISSUE TITLE
Use cryptography.io's AEAD in UmbralDEM

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#30]
It seems that after all, cryptography.io had AEAD implementations (although in the hazmat module, but that's OK). 

https://cryptography.io/en/latest/hazmat/primitives/aead/

We could update `UmbralDEM` (as per https://github.com/nucypher/pyUmbral/pull/29) to use this instead NaCL's Secret Box. This is not a priority, but I would like to have the possibility to use the Associated Data part of the AEAD to improve the overall integrity of the `(capsule, symmetric ciphertext)` bundle.

**Comment by tuxxy** [comment]
Yeah, this sounds great to me. I guess we're going to use ChaCha20-Poly1305 now?

**Comment by tuxxy** [comment]
ChaCha20-Poly1305 implemented in #33. Awaiting merge.

**Comment by tuxxy** [comment]
Merged.
