### ISSUE TITLE
Fix PRE interface

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#31]
I propose, as I have a few times on Slack, making PRE a module, which does `UmbralParameters` stuff at import time (with some global configuration options available) and just worked.  

This line appears in our codebase 18 times:

`pre = umbral.PRE(...)`

If we don't do something about it, it will end up sprayed all over our user's codebases as well.

Let's get it out!

**Comment by tuxxy** [comment]
Yeah, those are all in tests, though, as needed.

I'm not sure I see the benefit to this. For example, in the KMS, you'll only need a single instance of it somewhere and you can currently do this. In what case will users need more than one instance of PRE?

**Comment by tuxxy** [comment]
Unless I'm misinterpreting this and you're proposing something to get rid of this in our tests? We could still probably just declare an instance of it outside of the testing functions and in the top of each file or something.

**Comment by jMyles** [comment]
> In what case will users need more than one instance of PRE

I bet you misread the title. :-)

**Comment by tuxxy** [comment]
So you mean literally rewriting PRE as a singleton class? We don't need to do that, there are no demands for it.

**Comment by jMyles** [comment]
> singleton class

There is no such thing in Python.  I meant change it to a module. 

(I assumed you misread this as "PRE *was* a singleton.")

I don't really understand your question, then.  You just said above that there aren't use cases for more than one instance.

**Comment by tuxxy** [comment]
So, what exactly are you proposing we do about this then?

**Comment by jMyles** [comment]
It's a broken interface as is.  Where is the user supposed to import it?  Where instantiate it?  Then what, import it again form wherever they instantiated it?  What if this creates a circular import in their codebase?  Then they're supposed to dependency-inject it?  

This is clearly supposed to be a singleton.

Just make it singular; they import it (it does the params parts) they and use it.

**Comment by michwill** [comment]
We can have `pre = PRE()` inside umbral.py. Idk how it would play with multiprocessing and multithreading though. Or it could be in thread locals (like I did in the original prototype).

I do agree that it makes sense to do umbral.pre being an already instantiated PRE object because having `pre = umbral.PRE()` doesn't carry any logical information

**Comment by jMyles** [comment]
Sure, `pre = PRE()` makes it singular.

However, it also takes away all of the class / instance functionality, so why not just make it an instance?

I don't really see the need for it to carry state; params seems to be process-wide, right?

**Comment by jMyles** [comment]
Slack conversation: 

jmyles [10:08 PM]
OK, next: let's fix the PRE and params.
michwill [10:09 PM]
E.g. not having many PRE objects hanging around?
jmyles [10:09 PM]
Yeah.
tux [10:09 PM]
You only need one.
michwill [10:09 PM]
Exactly
tux [10:09 PM]
I am so confused, where is this an issue in a codebase that hasn’t implemented it yet?
michwill [10:10 PM]
That's why it can be instantiated right inside the module
tux [10:10 PM]
So, you guys just want `pre = PRE(UmbralParameters())` in umbral.py?
[10:10 PM]
then you can do `from umbral.umbral import pre`
jmyles [10:10 PM]
I mean... sure.
[10:11 PM]
But the right way to do it is to take the `class PRE(object)` line out and outdent everything.  :slightly_smiling_face:
michwill [10:11 PM]
That's probably the fastest way to do it
[10:11 PM]
Well
tux [10:11 PM]
I don’t think so
michwill [10:11 PM]
I am not sure if getting rid of PRE is always a good idea
tux [10:11 PM]
Yeah (edited)
jmyles [10:11 PM]
Why?
michwill [10:11 PM]
B/c not sure what openssl will do when you fork etc
jmyles [10:11 PM]
It *is* a singleton. (edited)
michwill [10:12 PM]
It could go crazy at forking and such
jmyles [10:12 PM]
Huh?
[10:12 PM]
So you're saying we'd offer a subclass of it?
tux [10:12 PM]
No
michwill [10:12 PM]
No, multiple instances, one per process / thread
tux [10:12 PM]
Yep
[10:12 PM]
This is how crypto libraries typically work, anyhow.
[10:12 PM]
for example, nacl
[10:13 PM]
`nacl.secret.SecretBox`
jmyles [10:13 PM]
This is very confusing.  What's the objection?
michwill [10:13 PM]
That was the difference between urllib3 vs urllib2 also, iirc. urllib3 required to create an instance where it's not quite logical, and that fixed threading problems of urllib2
[10:13 PM]
But it looked inconvenient for developers, so requests library wrapped urllib3
tux [10:14 PM]
I think I prefer to make `params` on `PRE.__init__` default to `UmbralParameters()`
michwill [10:14 PM]
So probably no one uses urllib3 directly, only through requests
jmyles [10:14 PM]
yeah
[10:14 PM]
Well look: I don't think that trying to cajole this into being threadlocal is sensible.
[10:14 PM]
It seems pretty much process-wide in every case that I can think of.
tux [10:14 PM]
Okay, so look at it this way: let’s do it like the way everyone else does.
jmyles [10:15 PM]
Sure - the way most python singletons are written is as modules.
[10:15 PM]
`import requests`
tux [10:15 PM]
Well, most crypto libraries just use it like nacl does it
[10:15 PM]
`nacl.secret.SecretBox`
jmyles [10:15 PM]
That's not a singleton.
[10:15 PM]
Totally different interface.
tux [10:16 PM]
`box = nacl.secret.SecretBox(key)`
[10:16 PM]
No, it’s not
jmyles [10:16 PM]
I don't even understand the connection you're making.
tux [10:16 PM]
`box.encrypt/decrypt`
[10:16 PM]
`box.KEY_SIZE`
jmyles [10:16 PM]
You're... saying you want to move encrypt/decrypt to a key-stateful object?
tux [10:16 PM]
`pre = umbral.PRE()`
[10:16 PM]
Where is the difference?
[10:17 PM]
`box = nacl.secret.SecretBox(key)` vs `pre = umbral.PRE()`
[10:17 PM]
You implement one per needed instance
jmyles [10:17 PM]
No no
[10:17 PM]
You can create multiple SecretBoxes - they're stateful per key.
[10:17 PM]
PRE inits (what are supposed to be) global params
tux [10:18 PM]
That’s actually not true
[10:18 PM]
you can implement a PRE object per curve
jmyles [10:18 PM]
Ahh
tux [10:18 PM]
per `UmbralParameters`
jmyles [10:18 PM]
Well, yeah, I know that you *can*
[10:18 PM]
But I thought that the intention was to make it global (and in fact, network-wide).
[10:18 PM]
@dnunez did say that.
[10:19 PM]
So, hmm, OK, then how do you propose the interface work?
tux [10:19 PM]
Exactly the way it works right now
jmyles [10:19 PM]
I don't think it makes sense to just sloppily init it at the bottom of the module; take the extra 45 seconds and outdent everything.
tux [10:19 PM]
I don’t want to make it module
jmyles [10:19 PM]
Well, it's broken right now.
tux [10:19 PM]
It’s not broken
[10:19 PM]
It works
jmyles [10:19 PM]
??!
[10:19 PM]
Did you read what I wrote?
[10:19 PM]
On the issue?
[10:20 PM]
Where do you put `pre = PRE(...)`?
[10:20 PM]
Where will we document as the right place for the user to do that? (edited)
tux [10:20 PM]
Really, the user should put it where they need
[10:21 PM]
it’s not like it spins up a ton of computation power, they can find a place to use a singleton, or use it as needed
[10:21 PM]
I still don’t see how this is _broken_
[10:21 PM]
Is this blocking you or something?
jmyles [10:21 PM]
So they're supposed to... init it everywhere they need it?  Like, in multiple modules?
tux [10:21 PM]
No, as it’s needed to be called, if they want. They can put it anywhere, it’s universal
[10:22 PM]
I don’t understand how it’s _broken_.
jmyles [10:22 PM]
This is clear as mud.  Can you sketch a quick documentation paragraph about how you envision this working?
[10:22 PM]
Maybe it's not broken, maybe I just don't understand. (edited)
tux [10:22 PM]
It’s the exact same as you would use NaCl
jmyles [10:22 PM]
No it isn't.
tux [10:22 PM]
`box = nacl.secret.SecretBox(key)`
jmyles [10:22 PM]
If it is, then it needs to be changed.
[10:23 PM]
If you are trying to emulate the `SecretBox`, you didn't do it quite right.
tux [10:23 PM]
I’m not trying to emulate anything
[10:23 PM]
I’m doing the way nearly every other cryptography library works
jmyles [10:24 PM]
I guess - let's see the doc.  It's not obvious to me.
[10:24 PM]
You are saying that you're doing it like `SecretBox`, but it isn't like that at all.
[10:24 PM]
I don't see the similarity.
[10:24 PM]
I *wish* it were like that.
tux [10:25 PM]
You instantiate it exactly the same way
jmyles [10:25 PM]
You don't pass global config data into `SecretBox`, you pass object state.
tux [10:25 PM]
Such is `UmbralParameters`
[10:25 PM]
We have a default that the user can use
[10:25 PM]
if they don’t like it, they can make their own (edited)
jmyles [10:28 PM]
Look: one of us is seriously confused.
[10:28 PM]
And honestly, I don't think it's me.
[10:28 PM]
Imagine this: (edited)
[10:28 PM]

```pre1 = PRE()
pre2 = PRE()

pre1.params.h != pre2.params.h
```

(edited)
tux [10:29 PM]
What is `h`?
1 reply
Today at 10:30 PMView thread
jmyles [10:29 PM]
I don't see why you are saying that you are doing this in a way that's similar to `SecretBox`.
[10:29 PM]
It's a parameter.
[10:29 PM]
Which, by default, is randomly generated.
[10:30 PM]
How do you get the same `pre` params across your codebase?  What's your vision of the correct, documented way to use this?
tux [10:30 PM]
Why do you need `h` and `u` to be the same across the codebase? (edited)
jmyles [10:31 PM]
Well, maybe they don't.  But it's *not* the same as `SecretBox`.  You can get a logically equivalent `SecretBox` object anywhere you need it by init'd with the same key.
tux [10:32 PM]
So, your point is that because these two points are generated at random means that this entire class needs to become a module now?
[10:33 PM]
I really am not seeing the issue here
jmyles [10:33 PM]
I mean... do we want users to init'd it again and again everywhere they import it?  And have different params for each?  That's what @dnunez said he doesn't want.  So when I see the class doing it, I say, "hey, this isn't what we talked about."
tux [10:33 PM]
just because they don’t have the same points that are supposed to be generated randomly
jmyles [10:34 PM]
I don't mean to be curt, but this seems like a silly discussion to me.  Are the params supposed to be the same process-wide by default?  If so, this is obviously not the right way to do that.
tux [10:34 PM]
No
[10:34 PM]
They don’t have to be
jmyles [10:35 PM]
OK, so you want them to be per-module by default?
tux [10:35 PM]
It’s used to do Schnorr signatures and the Schnorr protocol
jmyles [10:35 PM]
(ie, when a user imports PRE, they make a new params every time)?
[10:35 PM]
So?  What if they're splitting the labor of doing that across classes that live in different modules?  Nobody is going to expect different params every time they import it by default. (edited)
[10:36 PM]
(will they?)
tux [10:36 PM]
I don’t understand at all what you mean by splitting the labor across classes
jmyles [10:36 PM]
You're saying this is how other crypto libraries do this, but I can't immediately think of one.
tux [10:36 PM]
You could instantiate a global `UmbralParameters` and use that
jmyles [10:36 PM]
So that's going to be the documented approach?
tux [10:37 PM]
The `u` and `h` are used during split rekey
jmyles [10:37 PM]
The *user* has to instantiate global params?
tux [10:37 PM]
After that, it doesn’t matter — it’s in the ciphertext.
jmyles [10:37 PM]
But what if they want to - for any reason - get the same set of kfrags again?
tux [10:37 PM]
Why would they do that?
jmyles [10:37 PM]
They need to remember to hang on to that instance of PRE?
tux [10:37 PM]
Ciphertext should be different every time.
jmyles [10:38 PM]
I don't understand - an hour ago you were saying "there's no reason to have more than one instance," now you are advocating that the user need to init new instances for every use.  I think I'll benefit from just seeing your ideal use documented.  Maybe then it will click for me.
tux [10:39 PM]
I have no idea what to document for you
[10:39 PM]
you’re claiming taht you need the same ciphertext?
jmyles [10:39 PM]
Dude.
[10:39 PM]
Come on now.
tux [10:39 PM]
I am exceptionally confused heree
jmyles [10:39 PM]
Make documentation, just like you might for any other project, showing me how to use the PRE class in my project.
tux [10:40 PM]

```Using Umbral is easy:

from umbral import umbral


pre = umbral.PRE(umbral.UmbralParameters())
pre.encrypt(...)
```

jmyles [10:41 PM]
So I do that in any module where I need to use it, right?
tux [10:41 PM]
Sure
jmyles [10:41 PM]
So every module in my project will give a different result for the same input, right?
[10:41 PM]
Is that what you want?
[10:41 PM]
Can you point me to another crypto library that does that?
tux [10:41 PM]
Yes, that’s how encryption works
jmyles [10:41 PM]
Maybe it's more normal than I realized.
tux [10:41 PM]
Look at how nonces are used in nacl
jmyles [10:41 PM]
I usually think of encryption as utterly deterministic - the same input will result in the same output.
tux [10:41 PM]
they’re generated randomly
[10:42 PM]
It’s deterministic in the fact it can be reversed
jmyles [10:42 PM]
Well yeah man, but we're not talking about nonces here.
tux [10:42 PM]
but nonces are generated randomly
[10:42 PM]
it sorta is
[10:42 PM]
it’s a point used once
[10:42 PM]
call it a ponce
jmyles [10:42 PM]
It's not.
[10:42 PM]
It's used once *per module*.
[10:42 PM]
If I run it in a loop in the same module, it doesn't cycle.  It's not a nonce.
[10:42 PM]
Not in any way that that word is typically used in crypto.
tux [10:43 PM]
Then maybe we should update it after each use
jmyles [10:43 PM]
OK, now you're talking!
[10:43 PM]
If that's what you meant, then let's do that.
[10:43 PM]
That makes *much* more sense.
[10:43 PM]
However
tux [10:43 PM]
That’s not what I meant, but okay
[10:44 PM]
it literally doesn’t matter that this randomly generated point changes per instance
jmyles [10:44 PM]
@dnunez, whom can weigh-in on this later, said that he wanted it to be global (and for some params to even be network-wide)
[10:45 PM]
It does matter.  It's broken.  It doesn't do what any reasonable person will expect it to do.  Classes don't typically randomly mutate this way.  It's not what the user will expect.
tux [10:45 PM]
The user doesn’t need to worry about it
jmyles [10:45 PM]
If it's *supposed* to do that - and that's the spec, then let's make it do that and document it.
tux [10:45 PM]
similarly, a user doesn’t need to worry about the nonce generated per encryption in nacl
jmyles [10:45 PM]
(but again, I don't think that's what @dnunez wants)
tux [10:46 PM]
They can if they want, and it’s mostly just used as a counter if handled manually.
jmyles [10:46 PM]
The nonce is an intentional, engineered solution with documentation that does what it says it will do.  This, by contrast, reads as though it happens by accident.
tux [10:46 PM]
So, you’re asking for documentation on `UmbralParameters`, then?
jmyles [10:46 PM]
Both.
[10:47 PM]
I mean, I had imagined that `UmbralParameters` was going to be - *as we discussed* - relegated at least partly to a config role, with yaml read at runtime.
[10:47 PM]
(So, I had imagined that both PRE and UmbralParameters were going to be singletons)
tux [10:48 PM]
I don’t think it should be user editable
jmyles [10:49 PM]
(bagh, it looks like that conversation has been swallowed by Slack and not copied to github!)
tux [10:49 PM]
because if they change those params, then they could fuck up their users with the rest of the network
jmyles [10:49 PM]
I guess I don't understand - aren't you saying you want them to be able to pass their own `UmbralParameters` instance?
tux [10:50 PM]
No, if you want it to be _global_, then they should not be able to easily change them
jmyles [10:50 PM]
As I understand it, @dnunez's idea was that we'd (for example) include a config file with the KMS.
tux [10:51 PM]
Sure, but I don’t think it occurred to him that curious people might mess with that config and mess up their users unknowingly.
jmyles [10:51 PM]
Yeah, maybe.
[10:51 PM]
but I mean, that's not terribly high on the list of pranks and / or mishaps I don't think.
[10:52 PM]
Anyway: it doesn't make sense for it to have different parameters per init.  That's not expected behavior I don't think.  If that's really what you want, then I think it need to be documented.
[10:52 PM]
I really think it's better to just treat it like a singleton.
tux [10:52 PM]
meh, that’s actually pretty high imo
jmyles [10:52 PM]
This feels like over-engineering to me again.
tux [10:52 PM]
to hard code the params?
jmyles [10:52 PM]
No no
[10:52 PM]
I just mean to add class / instance infrastructure to PRE
[10:53 PM]
Instead of making it a simple, clean singleton of functions and globals
[10:53 PM]
`import requests`
[10:53 PM]
`requests.get(url)`
[10:53 PM]
simple, clean, obvious
tux [10:55 PM]
Well, let’s see what @dnunez has to say

**Comment by jMyles** [comment]
More Slack updates: 

dnunez [3:08 AM]
hi guys
[3:09 AM]
my turn to weigh in
[3:10 AM]
wrt to the class/module discussion, I'm afraid I'm not knowledgeable enough regarding threat-safety et al. so I cannot comment on that. But @michwill talked about potential problems of having it as a module, and I don't see any fundamental problem in being PRE a class. (edited)
[3:10 AM]
wrt to UmbralParameters they are thought to be network-wide
[3:11 AM]
the first important parameter is the curve
[3:11 AM]
`g` and `order` depend on curve
dnunez [3:12 AM]
and then generators `h` and `u` are used during the correctness and verification procedures. At the moment they are randomly generated, but simply because we needed a way of (1) obtaining generators `h`and `u` different than `g`, which is the default generator, and (2) avoiding any possible suspicion that we have additional information about the mathematical relation between `h`, `u`, and `g` (i.e., a backdoor). Now that I think about it, current solution is not good, since users wouldn't necessarily trust that we have created `h`and `u` randomly. I will devise a way to create `h` and `u` deterministically. Anyway, requirements (1) and (2) should be met. (edited)
2 replies
Last reply today at 9:43 AMView thread
dnunez [3:12 AM]
In the end, we need that alices, ursulas, and bobs use the same `h` and `u`. The UmbralParameters init method is there because at some moment we need to create them, but for our network we should probably distribute them somehow (as a file, for example, or whatever way you think it's better). So users shouldn't init UmbralParameters basically. Anyway, I think this discussion is probably my fault because of the way I created the UmbralParameters class. (edited)
[3:14 AM]
wrt to being umbral multi-hop, I'm afraid it's not
[3:15 AM]
in order to make it multi-hop is to remove the non-interactive transformation, but that has other implications
[3:16 AM]
the scheme would now be bidirectional (instead of unidirectional), transitive (instead of non-transitive), and of course, interactive (instead of non-interactive)

**Comment by jMyles** [comment]
dnunez Today at 3:12 AM
in #general
and then generators `h` and `u` are used during the correctness and verification procedures. At the moment they are randomly generated, but simply because we needed a way of (1) obtaining generators `h`and `u` different than `g`, which is the default generator, and (2) avoiding any possible suspicion that we have additional information about the mathematical relation between `h`, `u`, and `g` (i.e., a backdoor). Now that I think about it, current solution is not good, since users wouldn't necessarily trust that we have created `h`and `u` randomly. I will devise a way to create `h` and `u` deterministically. Anyway, requirements (1) and (2) should be met. (edited)
2 replies
michwill 2 hours ago
Oh, that is interesting. Can we derive `h` and `u` from `g`, for example?
michwill 2 hours ago
(e.g. deterministically)

**Comment by jMyles** [comment]
> In the end, we need that alices, ursulas, and bobs use the same `h` and `u`

I find this conversation very difficult.  Everybody is saying different things.  Last night, @tuxxy said that he viewed it as an *advantage* to have these params be different every time the class is init'd (which, for most users, will be per module).  

It is also my sense (as I said above) that the current interface is broken in the sense that we're forcing users to init a new PRE object all over their codebase, and once they do, they'll get different params.  Making it deterministic seems like a huge plus to me; then it will somewhat resemble `SecretBox`, which Tux put forward as an inspiration.

For the life of me, I don't understand the insistence on keeping all of the complexity that comes with making PRE a class.  We aren't using any of the features that come with class / instance infrastructure (you can see this yourself by grepping "self" in that class - it is used only as a way to reference other methods or as a way to access params, both of which obvious come free in a module).  

If multiple actors (let alone multiple processes or threads) need to share the same values for these parameters, then any idea that init'd a class is a route to thread safety is just kicking the inevitable locking work down the road and obfuscating the actual challenge.  There are many documented projects which use Twisted and PyOpenSSL.  It's possible that we may want to create a lock or queue facility for PRE operations.  And that can obviously live right on the module (again, there's no reason to ever init more than one of them).

**Comment by jMyles** [comment]
@tuxxy:  I also am struggling to understand the inner-workings of your mind re: code organization.

At our last homecoming, you were decrying the existence of classes in the first place, calling them useless.  You said that you didn't really see a need for classes except in video game programming, and that they don't particularly make sense for our code base.

Fortunately, @KPrasch and I were able to convince you of the expressive and organizational qualities of the class / instance interfaces in those times when they are useful.

However, now, you have an occasion where you want to turn a thing into a class, even though it doesn't have to be!  What happened to your principled stand in favor of functions and imperative organization!  Now is the time to let it out!

You are saying you are trying to take inspiration from other crypto projects, but I cannot find another case where a class is used this way.  The fact that you held up `SecretBox`, which is obviously a true class, with each member distinguished by its initial state (`key`), as an example is just absolutely dizzying.  Reading the source for `SecretBox`, it does not in any way remind me of `PRE`.

Look: at the end of the day, no matter how we decide to organize the code, PRE ("Proxy Re-Encyrption") is not a class of things.

You don't ever pause in your life and say, "Look at all these proxy re-encryptions - a blue one, a yellow one, one with three legs!"  

That's what *classes* are for - to describe phenomena for which many instances are *classifiable* under a single taxonomy, with templating for behavior and state.

This thing is *not* a class of things.

**Comment by jMyles** [comment]
If we do decide that this thing is supposed to be a class (ie, there is a reason to have multiple instances), then we need to fix it in the following ways:

* Instantiating with the same arguments gets an object that is materially the same (ie, in this case, with the same values for `h` and `u`
* Values for `h` and `u` can be harvested from one instance in such a way that allows deterministic creation of another
* Ships with sane defaults that give the user the same values across instances *if they pass nothing*.  I am still of the mind that it makes sense to push this down into a config facility; maybe a yaml file.

*If* those things are put in place and *if* there is a use-case for multiple instances, then of course PRE is indeed a class and it makes sense to keep some parts of the current organization.

**Comment by tuxxy** [comment]
> Last night, @tuxxy said that he viewed it as an advantage to have these params be different every time the class is init'd

I never said this. I ceded that these options could be randomly generated after every use to please your argument. Your arguments confuse me into talking on several points at once. The part I claimed an advantage of is differing ciphertexts for same inputs in encryption algorithms.

> At our last homecoming, you were decrying the existence of classes in the first place, calling them useless. You said that you didn't really see a need for classes except in video game programming, and that they don't particularly make sense for our code base.

This is not at all what I said, in fact it is quite the bastardization of what I said. I have a strong distaste for OOP. I find that it leads to large amounts of bloat and hidden complexity. I never once claimed that classes were useless, in fact I claimed the opposite -- classes and structs serve as means to organize data and code.
The point where it goes too far is inheritance -- I despise inheritance. It leads to "clever code" that is unnecessarily complex and hides logic. This leads to security issues and bugs hidden beneath layers and layers of complexity.

This is not the current discussion, though.

>You are saying you are trying to take inspiration from other crypto projects

Again, not saying this either. I'm using other crypto projects as examples to how ours currently works. We have not modeled anything off of any other projects.

>Look: at the end of the day, no matter how we decide to organize the code, PRE ("Proxy Re-Encyrption") is not a class of things.

You're right, I'd rather put it in a struct.

I'm beginning to be very annoyed by this. Can we please pick something and _just move on_? These arguments waste valuable productive time.

**Comment by jMyles** [comment]
Well, man, I don't know what to tell you.  I'm also annoyed by this.  Either fix it or at least stop protesting the application of reasonable, normal best practices.

If it's truly a class, make it a class per my comment above.

If not, then don't make it a class.

The application of arbitrary complication here is really bewildering.

**Comment by jMyles** [comment]
@tux, I'm not thrilled over the idea that I'm somehow misquoting you.

> I never said this. I ceded that these options could be randomly generated after every use to please your argument.

Immediately before this (see above), you asked me to "think of it as a Ponce, [point nonce]" as if this is some kind of intentionally engineered uniqueness.  Now, @cygnusv says, "In the end, we need that alices, ursulas, and bobs use the same h and u."

So which is it?  I'm not mis-characterizing your position here - these are two different possibilities.  One of them needs to be selected.  Please do that.

> I never once claimed that classes were useless, in fact I claimed the opposite

I mean, sure - we were all being hyperbolic.  But it was an hours-long discussion to finally convince you even to adopt obvious classes like `CFrag`, `PublicKey`, and `Signature`.  Listen, I'm glad you came around - it's great that we can change each other's mind sometimes.  But I don't think it's wholly unfair to suggest that it's inconsistent now to insist on class infrastructure for a concept that isn't even meant as (nor used as) classification.  

> You are saying you are trying to take inspiration from other crypto projects
> Again, not saying this either.

@tuxxy, you literally said (see above), "Okay, so look at it this way: let’s do it like the way everyone else does."  I don't think I'm mis-characterizing your view here.  The problem is that you are proposing doing it differently than is typical for the type of control structure you're trying to advance.

One thing you and I agree on: this is way too time- and energy-consuming a discussion.  Go back to my first question above in this comment.  Let's have an answer that enjoys team-wide consensus and then quickly move forward from there.

**Comment by cygnusv** [comment]
Hi guys,
Is deterministic generation of UmbralParameters + PRE as a class an
acceptable solution here?

I think my initial code where parameters we're generated randomly has
proven to be disastrous, for several reasons.

If that solution is acceptable then I'll write tomorrow the code for
deterministic parameter generation. In the meantime, you can simply use `h
= g` and `u = g` as a temporary method.

Sounds good?

**Comment by jMyles** [comment]
@cygnusv:  Yes, I think it's acceptable!  :-)

I wish it were a singleton, but as @michwill points out, it might make it easier for people to do the wrong thing.  

My comment above (https://github.com/nucypher/pyUmbral/issues/31#issuecomment-360202905) has what I think is the prescription for turning this into a true class - does that look about right to you?

**Comment by jMyles** [comment]
Final Slack convo on the matter (saved here for posterity):

michwill [1:46 PM]
Anyway. It is possible to make them as hash(hash(g) + "whatever"), converting to points with priv2pub if needed
jmyles [1:47 PM]
Yeah.
[1:47 PM]
And then the "whatever" is a project tag
[1:47 PM]
"nucypher-kms"
michwill [1:47 PM]
Perhaps, hash(serialize (g)+"...")
jmyles [1:47 PM]
then all kms nodes have the same params
michwill [1:48 PM]
So with the module it is tricky
[1:48 PM]
We can and probably should make it a singleton
jmyles [1:48 PM]
Yeah?  It seems way simpler to me.
michwill [1:48 PM]
But
[1:49 PM]
We want to avoid users accidentally sharing the same pre objects in multiple threads
jmyles [1:49 PM]
But we'll have to do that anyway.
michwill [1:49 PM]
No
[1:49 PM]
pre object has to be created per thread at least
[1:49 PM]
Otherwise openssl can go crazy
jmyles [1:50 PM]
Well, think it all the way through though:
michwill [1:50 PM]
It can look like the same thing in the code though
jmyles [1:50 PM]
if 10 PRE objects share the same params (literally `is` the same), then we have the problem no matter how many instances.  Conversely, if PRE is a singleton, then we have just one place where we need to consider thread safety.
[1:50 PM]
So
[1:51 PM]
We can either ensure that multiple instances always get a deepcopy (meh)
[1:51 PM]
or we can throw some simple safety tooling into the module (ideally, IMO, a queue) (edited)
michwill [1:52 PM]
Instances shouldn't share same objects for g,h,v and so on
jmyles [1:52 PM]
OK, so we do either a deepcopy or re-create them deterministically?
michwill [1:52 PM]
But the can perfectly be same number mathematically
[1:53 PM]
Re-create imo
jmyles [1:53 PM]
OK, I'm OK with that.
[1:53 PM]
(if it's lightweight enough to justify)
michwill [1:53 PM]
I don't know what deep copy will do with openssl stuff
[1:53 PM]
Well, per thread, right?
[1:53 PM]
So we can have threadlocal
jmyles [1:54 PM]
...but why don't you like the idea of a queue, where we force all PRE operations in the same process through a single thread?
michwill [1:54 PM]
Well.. perhaps it is fine with the current state of gil indeed
jmyles [1:55 PM]
And I guess, as a bigger picture - why does any of this belong in pyumbral?  Like, my view is that pyumbral can take no opinion on thread safety (or even concurrency at all) and just the user handle it.
[1:55 PM]
And then, in the KMS, we'll show a really simple, elegant system for enforcing thread safety.
michwill [1:56 PM]
In kms we can have locks, yes
[1:56 PM]
But I am afraid, outside KMS users won't do it and get horrible things
jmyles [1:57 PM]
Web apps, right?
[1:57 PM]
That's my concern too.
michwill [1:57 PM]
Having a way to create a pre objects is probably one way to move this concern out of pyumbral
[1:58 PM]
At the cost of extra "meaningless" line
jmyles [1:58 PM]
OK, so (as @dnunez just said on github) leave it a class but make it deterministic per-project.
[1:58 PM]
That's acceptable.
michwill [1:58 PM]
Yes
[1:58 PM]
Let's do that
jmyles [1:58 PM]
:+1: (edited)
