### ISSUE TITLE
Why are 5 tests commented out in test_umbral?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#6]
There are five tests - the last four of which look very interesting - commented out.  Where are we on these?

**Comment by cygnusv** [comment]
I'm on it! There were some pending things before I could uncomment it. I also need to adapt them to the new syntax of Umbral.

**Comment by jMyles** [comment]
@cygnusv: Beautiful work man, this module now reads very nicely.

Here's an example of a couple lines that really made me feel engaged and excited to read:

```
    # Alice tries to frame the first Ursula by sending her a random kFrag
    fake_kfrag = kfrags[0]
```

**Comment by cygnusv** [comment]
Thanks man! just changed a little bit some variable names in the tests to comply with our new naming scheme (capsules & co.)

**Comment by jMyles** [comment]
Hey @cygnusv, I notice that you re-commented-out three of them, but it's not immediately obvious to me why.  Do they just need to be re-written to use the methods on `Capsule`?

**Comment by tuxxy** [comment]
@cygnusv I'm assuming that this is because that challenge protocol stuff isn't nailed down 100% quite yet?

I'd like to close the issue if we can, just need some clarification before I do that.

**Comment by KPrasch** [comment]
PR #63 fixes this.
