### ISSUE TITLE
UserWarning: Unknown distribution option

### ISSUE THREAD

**Issue by tpmccallum** [nucypher/pyUmbral#69]
Hi,
Just curious about the best installation option. I am using the following command and receiving the warning shown below.
Many thanks
Tim
```
sudo python3 setup.py install

```
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
 warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python3.5/dist-packages/umbral-0.1.egg-info
Writing /usr/local/lib/python3.5/dist-packages/umbral-0.1.egg-info
```

**Comment by jMyles** [comment]
Hey @tpmccallum.  How are you?

First question: why are you attempting to install with `sudo`?

**Comment by michwill** [comment]
Always good to install in virtual environment. We use `pipenv`, but also you can use `virtualenv`. Also you can install in home directory with `pip3 install --home -e /path/to/checkout`

**Comment by tpmccallum** [comment]
Super, thank you so much @michwill really enjoyed your video also < https://www.youtube.com/watch?v=hug1LRznsQI >
Kind regards
Tim

**Comment by KPrasch** [comment]
Hey @tpmccallum!  
The NuCypher team uses Pipenv for dependency management on pyUmbral. Check out the Pipenv docs here: https://docs.pipenv.org/.  You _can_ manage a virtualenv manually, but here is the recommended installation procedure:

- To install pipenv: `sudo pip3 install pipenv`
- To install pyUmbral dependencies: `pipenv install`

**Comment by tpmccallum** [comment]
Thank you @KPrasch 
This worked, I am in the shell :)
