### ISSUE TITLE
CiphertextCombined -=> Capsule?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#7]
As you can see from my PR, I had called this encrypted key a `combined_critical_mass`.  

But since we always run `decapsulate` on it, does it make sense to call it a `Capsule`?

**Comment by tuxxy** [comment]
I think I prefer `EncapsulatedKey` more a la KEM.

**Comment by jMyles** [comment]
But if someone is building something other than a KMS, this won't be a key, will it?  (or do I misunderstand?)

And yeah - what's the "KEM" in `CiphertextKEM`?

**Comment by tuxxy** [comment]
https://en.wikipedia.org/wiki/Key_encapsulation

**Comment by tuxxy** [comment]
> But if someone is building something other than a KMS, this won't be a key, will it? (or do I misunderstand?)

This will always be a key.

**Comment by jMyles** [comment]
Help me understand - why will it *always* be a key?  Can't it be an encapsulated message of arbitrary data?  For example, in the scenario depicted by @michwill's test here:

https://github.com/nucypher/nucypher-kms/blob/master/tests/crypto/test_encrypting_keypair.py#L39

Isn't `b"hello_bob"` the thing that will be getting encapsulated in an umbral implementation?  Or am I missing a layer?

**Comment by tuxxy** [comment]
It can be arbitrary data, yes (up to a certain size for nominal performance). However, in these schemas, the data passed for encryption is usually a key. This is the basis of ECIES and KEM based cryptosystems.

I have always seen this as more of a test than anything meaningful.

**Comment by tuxxy** [comment]
So, you would do:

1. Generate key.
2. Encrypt data with key from step 1.
3. Encrypt key with Umbral.
4. Share encrypted key.
5. Re-encrypt.
6. Decrypt key
7. Decrypt data.

**Comment by jMyles** [comment]
Right - I understand the basic for flow the KMS.

But I think it's confusing / unnecessarily complicated to name this class `EncapsulatedKey` when it is really just encapsulated arbitrary data. 

I do like the convenience method (currently called `encapsulate`) that creates the symmetic key so that Alice doesn't have to get bogged down by those internals, but maybe we just change this to `create_encapsulated_key`, which then performs steps 1 and 3 from your directive above.

**Comment by tuxxy** [comment]
Well in the scheme itself, which is based on ECIES, the encapsualated data should preferably be a key.

Yes, someone can theoretically use arbitrary data, but this is probably not suggested. I still need to familiarize myself with the security of arbitrarily sized inputs and padding and whatnot with this system, and those things could be of concern.

I'd venture to say that if you're using arbitrary data in this scheme, you are using it _wrong_ and venturing into "hazardous material" territory.

The security of asymmetric cryptosystems isn't as great as symmetric encryption, either. It's a best practice as well, too.

**Comment by tuxxy** [comment]
Furthermore, we intend on streamlining the process of encryption/decryption to not allow the user to make such mistakes.

By implementing symmetric encryption in the scheme for the user, and having the user provide the data (the arbitrary data you suggest) to the system, we can enforce security and best practices.

**Comment by cygnusv** [comment]
Umbral follows what it's called in public-key cryptography a KEM/DEM approach (Key Encapsulation Method/Data Encapsulation Method), Basically, this means that the public-key encryption process is separated in two parts: first the Key Encapsulation Method consumes the recipient's public key and produces a symmetric key and an "encapsulated key", and second the Data Encapsulation Method consumes the previous symmetric key to actually encrypt the data. For the decryption, the KEM consumes the "encapsulated key" to recompute the symmetric key, so the DEM can decrypt.

As you can see, the "encapsulated key" is not related to the actual data you are encrypting, regardless if you are encrypting a message, a key, or whatever. It is just a naming convention that already exists in cryptography.

**Comment by jMyles** [comment]
Ahh, I see.  

OK, then `EncapsulatedKey` does probably make more sense, although I might still find it easier to reason about if it subclassed `Capsule`, so that the "key-ish" parts are separated from the "encapsulating" parts.

**Comment by cygnusv** [comment]
I do like the term `Capsule' although there are several particular places where it could be used, mostly for some of the class names. A proposal:

1. CiphertextKEM --> Capsule, or perhaps OriginalCapsule
2. CiphertextFrag --> CapsuleFrag (it's still a cFrag!)
3. CiphertextCombined --> (Combined/Restored/Reassembled/...)Capsule

**Comment by tuxxy** [comment]
I give a _strong_ +1 for `CapsuleFrag`.

**Comment by jMyles** [comment]
This is beautiful.

For the third, I like "ReassembledCapsule" I think - is "reassemble" what you do with fragments of something?

**Comment by jMyles** [comment]
Yeah, `CapsuleFrag` is a definite upgrade.  Makes it very easy to explain to someone if they've never heard of m/n or PRE.

**Comment by tuxxy** [comment]
I'm not sure how much I like `ReassembledCapsule`. It's quite the mouthful. I think I prefer `CombinedCapsule` because it matches quite succinctly with what is happening in the code.

**Comment by jMyles** [comment]
I think this is not so bad:

`capsule = RebuiltCapsule(...)`

But also, maybe we change `combine`?

I like this kind of thing:

`capsule = rebuild_capsule_from_fragments(cfrags)`

**Comment by cygnusv** [comment]
You English-speaking guys decide that one :-P

By the way, we could change the name of the Combine method so it matches whatever we decide with the new name of CiphertextCombined (e.g., if we go for Reassemble). But not something too verbose, please!

**Comment by jMyles** [comment]
Yeah, I like "rebuild" / "rebuilt" better than "combine" / "combined"

It doesn't add verbosity, but does lend identity.  If someone is reading this and they say, "where did that capsule come from?"  It might not help them to know that it is "combined," but knowing that it is "rebuilt" will very likely set them on the right track.

**Comment by tuxxy** [comment]
I am more partial to `reconstruct` I think because it fits more with Adi Shamir's original paper where his secret sharing is defined.

**Comment by jMyles** [comment]
Ahh, yes, `reconstruct`!

`capsule = reconstruct_from_fragments(cfrags)`
`>>> capsule `
`... ReconstructedCapsule object blah blah blah`

love it.

**Comment by cygnusv** [comment]
Sold.

**Comment by tuxxy** [comment]
Actually, I think `reconstruct_capsule` would be preferable. The type hinting would be the answer to not using verbose names as such.

**Comment by jMyles** [comment]
OK, that's fine - if there's no other way to reconstruct the capsule other than from fragments.

**Comment by cygnusv** [comment]
So in summary:

1. CiphertextKEM --> Capsule
2. CiphertextFrag --> CapsuleFrag
3. CiphertextCombined --> ReconstructedCapsule

**Comment by tuxxy** [comment]
Indeed, this is lovely.

**Comment by jMyles** [comment]
I'm a bit wary of making type hints required reading for users because I suspect we may have an influx of readers who are already power-readers in other languages, and type hints may be a little daunting for them.  But of course I still want to use them.  But I like thinking about them as being more for us.

**Comment by jMyles** [comment]
@cygnusv yep, that's a winner.  The only unturned stone is whether, per  your initial message, we want `CiphertextKEM` to turn into `OriginalCapsule`.

Right now, I'm imagining `OriginalCapsule` and `ReconstructedCapsule` both inheriting from `Capsule`.

**Comment by tuxxy** [comment]
I'm unsure about that, it depends on how we're going to handle some of the elements. That's for another day, though.

**Comment by jMyles** [comment]
Eh, Now is Better Than Never.  I'm think I'm preferring to do it that way from the beginning.

`class OriginalCapsule(Capsule):
    ...
`

`class ReconstructedCapsule(Capsule):
    ...
`

**Comment by cygnusv** [comment]
But what would be the advantage of that inheritance? I mean, what does a generic Capsule do? I personally don't see it. In fact, I like more Capsule than OriginalCapsule.

**Comment by jMyles** [comment]
So they'll be completely disparate classes?

I bet they'll end up repeating things like `__add__`, `__radd__`, `__repr__`, and probably even some logging logic if we go that route.  

Currently, if you squint your eyes, their `__init__` is exactly the same, but put `_prime` after two names and change `s` to `x`.  That suggests to me that they're meant to inherit from a common super.

**Comment by tuxxy** [comment]
@jMyles `__add__`, `__radd__`, etc won't be implemented on these.

These are essentially utility classes that allow us to perform operations on them passing them around easier. They also handle some serialization if needed, that's about it.

`__repr__` would pretty much call the serialization function for it.

In my opinion, the elements given don't really require the complexity of an inheritance and yet-another-class.

**Comment by jMyles** [comment]
You think we won't want to add them to other objects, having the result be a bytestring that we send over the wire?  That's how much of the KMS works at the moment.  Have you rethought that?

**Comment by tuxxy** [comment]
I don't think you have a clear vision of how these objects are utilized in the code here.

All of that can be simply handled by calling the serialization functions `to_bytes`/`from_bytes` that have yet to be built.

**Comment by jMyles** [comment]
Well, you're right that I don't have a clear vision of methods that aren't written yet.  :-)

Why `to_bytes` instead of `__bytes__`?

I predict that, in time, it will turn out to be a more complicated decision to maintain these as two separate classes, even though they represent a shared underlying metaphor, then to have a clear place for logic that gets shared between them.

**Comment by jMyles** [comment]
But fine, we can call the original capsule `Capsule` if you want, and then add `CapsuleBase` someday if we want.

**Comment by tuxxy** [comment]
There is no logic to share, that's what we're saying.

I think we both prefer `to_bytes` over `__bytes__` for a this one particular reason -- typically, in cryptographic libraries, it's always nice to be explicit about what is being serialized, e.g. `capsule.to_bytes()`.

Where in the `to_bytes` method there might be some standard specific stuff going on. For example, in our `Point` class we tack on some bytes and whatnot.

Whereas with a `__bytes__` method-call, it just feels like you're directly converting it to a literal bytestring of itself which just isn't the case. It feels deceiving.

**Comment by cygnusv** [comment]
Wrt to the challenge, recall that Bob wants to know if a CapsuleFrag is correctly computed, so it challenges Ursula to prove this. Ursula sends him a ChallengeResponse, which he can use to check if the CapsuleFrag is good or not. That's the current state.

Perhaps something like FragmentProof? I don't know. I kinda liked the Challenge and ChallengeResponse names, reminds me of cryptographic "challenge/response protocols".

**Comment by tuxxy** [comment]
@cygnusv I didn't have any issues with those names and thought similarly to you on the challenge/response aspect.

**Comment by jMyles** [comment]
I too like these names, and like them better than something like `FragmentProof`.

**Comment by cygnusv** [comment]
OK so we leave it as it currently is then.

**Comment by michwill** [comment]
Also I'm quite used to the concept "tests are docs" (to some degree). Should we have tests which show the types to the reader when we finalize on those?
E.g.:
```
assert isinstance(cfrag, CapsuleFrag)
```
(although I understand that with Python's typing and mypy they can be implicitly tested, I just meant tests ~= documentation)

**Comment by jMyles** [comment]
@michwill: Yeah, this is the one case where I actually like type assertions: when you are trying to introduce the reader to a class.

**Comment by jMyles** [comment]
This Issue is materially closed by @cygnusv's awesome work in 6bbfa48.

For further discussion on the names of the various `Capsule`-like objects, see #10.
