### ISSUE TITLE
Code update 

### ISSUE THREAD

**Issue by tpmccallum** [nucypher/pyUmbral#70]
Hi,
I am trying to run the demonstration as presented by John Pacific at < https://www.youtube.com/watch?v=x-HYMufPhVo >

It seems that the code here in nucypher pyUmbral is different to the code in the above YouTube demonstration.

For example running the following command

```
alice_pub_key = alice_priv_key.get_pub_key()
```
as per the video demo results in the following error

```
AttributeError: 'UmbralPrivateKey' object has no attribute 'get_pub_key'
```

If I run the following command to peer into the Umbral library's functions

```
dir(keys.UmbralPrivateKey)
```

I see that there is a function called get_pubkey (as apposed to the above get_pub_key)

I also note that the umbral.PRE() method is missing from the code base. 

Is it possible that the umbral code is out of sync with what was used in the video demo? Or is there another place I can get code to perform the same task (as the video demo) on my own PC?

Many thanks
Tim

**Comment by michwill** [comment]
Our `umbral` library is still in development, so changes pretty often. The up-to-date API you can see in this test: https://github.com/nucypher/pyUmbral/blob/master/tests/test_umbral.py#L47

**Comment by tuxxy** [comment]
@tpmccallum Hey, I'm tux AKA John Pacific! :)

It's awesome to see your interest in using pyUmbral, might you be at ETH Denver this weekend? I'll be demoing it there as well!

Anyway, sorry about the variations between the video and the current code. This video was recorded before a bunch of changes were made.

[I went ahead and updated the demo code for you.](https://gist.github.com/tuxxy/8130624f4f2579d0ff457ece101154a8) If you have any questions, you can make an issue here on Github, email me at john@nucypher.com or join our discord and ask where we all hang out.

Anyway, sorry again about the variations. I'm going to upload the code into the repo soon. :)

**Comment by tpmccallum** [comment]
Hi @michwill and @tuxxy 
Thank you so much, I am watching ETH Denver on-line as I am in Queensland, Australia.
Looking forward to working with pyUmbral again today. Thanks again for your help and quick responses, much appreciated.
Kind regards
Tim
