### ISSUE TITLE
Why these parameters?

### ISSUE THREAD

**Issue by jMyles** [nucypher/pyUmbral#8]
In `test_umbral`, we reuse this same set of parameters for values of `m` and `n` in several tests:
```
    (1, 1),
    (3, 1),
    (3, 2),
    (5, 4),
    (10, 8),
```

I think it makes sense to have a quick comment next to each of these explaining what new thing is tested by virtue of including it.  So:

```
    (1, 1),  # Works with a single kfrag.
    (3, 1), # Works when n is > 1, m is not.
    (3, 2), # Works when both are greater than 1.
    (5, 4), # ???
    (10, 8), # ???
```

**Comment by michwill** [comment]
To be fair, these comments wouldn't be of any use to me. But no problem including them.

At least, I had a good thought: should we test also `m=n > 1`?

**Comment by jMyles** [comment]
Yes I think so; good point @michwill.

And if I may ask: if these comments are superfluous in your mind, can you explain the test surface being demonstrated by the last two?

**Comment by michwill** [comment]
To me, the last two would just look like "testing with more kfrags". I'd be quite happy replacing them with one like "30 of 50"

**Comment by jMyles** [comment]
I see.  Well, if that's so, I'm interested to know what "correctness" about the logic we reveal merely by virtue of increasing the number of kfrags.  Do we need a test for 100?  1000?  10^256?

I'm inclined to reduce the number of parameterized tests to those which give a unique perspective on correctness of the logic.

**Comment by michwill** [comment]
"30 of 50" is the number I had in mind for using in real network, that's why I thought makes sense to test with it.
All others makes sense to do with small numbers for the sake of speed of the test

**Comment by cygnusv** [comment]
Well, @jMyles is right in that these parameters are very arbitrary. I can't imagine any potential difference between the execution of (3, 2) and (5, 4), to be honest, but somehow I ended up adding them, just because. 

Perhaps, what it makes sense to me is something like this:

```
(1,1)    # Regular re-encryption with no split-key
(small_n, 1)   # Testing a potential edge-case (minimum number of Ursulas)
(small_n, small_n)   # Testing another potential edge-case (max number of Ursulas)
(small_n, 70% of small_n)   # Testing a typical m/n ratio, but in a small scale
(somewhat_real_n, somewhat_real_m)  # Testing potential real figures
```
where `small_n` could be anything between, say 3 and 10. 
For the last case, 30 out of 50 seems about right for a "real" test case, in my opinion.

**Comment by tuxxy** [comment]
I think 6bbfa48d7863a580461b4098ea6afecad0d13dd8 closes this issue out.
