### ISSUE TITLE
Non-re-encryptable capsules

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#83]
It is possible to make capsules in such a way that it's impossible to reencrypt them to others. Do we want this? I guess we do.

**Comment by jMyles** [comment]
Interesting - what's the use-case here?  The person creating the capsule can always just create another one, right?  It's not immediately obvious to me what power dynamic is altered by this.

**Comment by tuxxy** [comment]
I think it would be cool to have this be the result after re-encryption such that:

`ReKey(Rekey(capsule))` fails.

**Comment by jMyles** [comment]
Maybe I just don't have my head on straight yet for the day, but what are you depicting with `ReKey` here?  (and did you mean to spell "`Rekey`" differently or is that an accident?)

**Comment by tuxxy** [comment]
I meant it as `ReEncrypt`, updated.

**Comment by tuxxy** [comment]
This does fail, currently. FYI, but for different reasons than making it completely impossible to re-encrypt a capsule.

**Comment by michwill** [comment]
Yeah, I think the underlying algorithm is multi-hop. Of course, we re-encrypt for the ephemeral key. Interesting to know what @cygnusv is thinking of.
As for use case, i have one for a multi-hop unidirectional scheme..

**Comment by michwill** [comment]
Another thing which is possible and would be nice - to allow decentralized key rotation for capsules (where the owner has access to both private keys for a short time)

**Comment by tuxxy** [comment]
Why would you need that to be decentralized?

How would that work, btw? The data is still encrypted with the original capsule key.

**Comment by michwill** [comment]
The data is still encrypted with the original capsule key, it's just a way for Alice to change her encrypting keypair and change the capsules accordingly.

The problem of just re-encryption like this is that it's essentially bi-directional (so, a malicious Ursula can hold onto the rekey and transform data back when needed). That's why splitting the trust is beneficial here

**Comment by tuxxy** [comment]
Ah, I see your point.

**Comment by jMyles** [comment]
We're not moving on this, right?  I propose closing wontfix.

**Comment by cygnusv** [comment]
yeah, let's close it for now.

**Comment by wachainio** [comment]
> Yeah, I think the underlying algorithm is multi-hop. Of course, we re-encrypt for the ephemeral key. Interesting to know what @cygnusv is thinking of.
> As for use case, i have one for a multi-hop unidirectional scheme..

Can you tell us about your multi-hop unidirectional scheme? Our project needs。
