### ISSUE TITLE
Shortcut method to get Cryptography.io keys from Umbral keys

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#84]
Current way is through methods in BigNum and Point classes. But perhaps it has more sense to offer such methods in Umbral keys. We can of course offer them in both places, but it seems more likely to be used in Umbral keys.

Related:
https://github.com/nucypher/nucypher-kms/pull/178/commits/53a0a33f6a68068a579561c9dbd9c4b32b5b001a#diff-f8cdf78f1ab20bfd277c9666b059217eR115

**Comment by tuxxy** [comment]
You can currently get a Cryptography.io public key via `Point.get_cryptography_pubkey`.

Are you wanting to get private keys too? Currently, I don't like that this sits on Point and would prefer it elsewhere.

**Comment by cygnusv** [comment]
I mean having a direct method in Umbral keys, rather than having to access the internal BigNum (in case of UmbralPrivateKey) or Point (in case of UmbralPublicKey)
