### ISSUE TITLE
Some tests create re-encryption keys from Alice to Alice

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#87]
Some tests do something weird, IMHO. Instead of using Alice and Bob as delegator and delegatee, they use Alice for both. For example:
```
def test_challenge_response_serialization():
    priv_key = pre.gen_priv()
    pub_key = pre.priv2pub(priv_key)

    _unused_key, capsule = pre._encapsulate(pub_key)
    kfrags = pre.split_rekey(priv_key, pub_key, 1, 2)
```

Is this intentional? If so, what's the rationale for that? 
I'm currently preparing a PR with some improvements, so I can change this if necessary.

**Comment by tuxxy** [comment]
Hmmm...

Not sure that it's intentional, but feel free to change them. :)

**Comment by KPrasch** [comment]
There is a PKE test in `test_simple_api` that uses only Alice's keys (without split key); Nonetheless in  `test_challenge_response_serialization` this looks unintentional, to me.
