### ISSUE TITLE
Drop pre.gen_priv() and pre.priv2pub()?

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#90]
We currently have two different ways of producing public and private keys in Umbral:

- Through the PRE class:

```
    priv_key = pre.gen_priv()
    pub_key = pre.priv2pub(priv_key)
```
- Through the UmbralPrivateKey class:
```
    priv_key_alice = keys.UmbralPrivateKey.gen_key()
    pub_key_alice = priv_key_alice.get_pubkey()
```
I'd prefer to have just one, preferably the second. What do you think?
As mentioned in my last issue, I'm preparing a small PR so I can make this change if you agree.

**Comment by cygnusv** [comment]
I just noticed that there are differences between the two. The first outputs the raw BigNum/Point, while the second the wrapper classes. Anyway, I still think we should drop the first.

**Comment by tuxxy** [comment]
Yeah, we can drop `gen_priv` and just generate a random `BigNum` instead. 

The second is more useful for obvious reasons.
