### ISSUE TITLE
Avoid using private key for signing

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#97]
There are certain places where Alice's private key is used for signing data (e.g., signature of kfrags). This should be avoided. 

This implies that a separate pair of signing keys or a signing function should be passed in. This can be made as an optional argument, so in case this is not provided, then the original approach (i.e., using Alice's private key) is used, since it's better than no signature at all.

**Comment by michwill** [comment]
Oh wow. Do we use Alice's _encrypting_ private key for signing?

**Comment by cygnusv** [comment]
Yeah, that's my fault. I didn't realized at that moment

**Comment by jMyles** [comment]
Right, so we'll pass a signer (such as a `SignatureStamp` instance) in the KMS implementation.

**Comment by cygnusv** [comment]
Yep, that's the one. The mathematical operations in there are the actual computations to perform the Schnorr signature, so we don't have to worry about that if we change it to, say, ECDSA. We only need a function to sign and another to verify.

Basically, what I was doing there is to obtain a signature of `[id_kfrag, pub_a, pub_b, u1, xcomp]` (see  line https://github.com/nucypher/pyUmbral/blob/master/umbral/pre.py#L309)

**Comment by jMyles** [comment]
...huh?  You want to stop using the Schnorr sig and instead use ECDSA?

**Comment by jMyles** [comment]
Closed in #145.
