### ISSUE TITLE
Consistent use of UmbralParameters in the main PRE API

### ISSUE THREAD

**Issue by cygnusv** [nucypher/pyUmbral#99]
Currently, `UmbralParameters` is an input parameter of `split_rekey()` and `reencrypt()`, but not in `encrypt()` and `decrypt()`. Strangely, it is a parameter of internal functions like `_encapsulate()`, `_decapsulate_original()` and `_decapsulate_reencrypted()`.

I propose to remove it from the internal functions, and put it only in the public facing ones.

**Comment by tuxxy** [comment]
Resolved in #104/#102
